export type RarityTier = 'common' | 'uncommon' | 'rare' | 'epic' | 'legendary';
export type Region = 'UK' | 'IE' | 'EU' | 'US' | 'CA' | 'AUS' | 'NZ' | 'ZA' | 'JP' | 'IN' | 'BR' | 'GLOBAL';
export type Habitat = 'river' | 'lake' | 'reservoir' | 'sea' | 'estuary' | 'ocean' | 'canal';
export type Season = 'spring' | 'summer' | 'autumn' | 'winter';
export type TimeOfDay = 'dawn' | 'morning' | 'midday' | 'afternoon' | 'dusk' | 'night';
export type ConservationStatus = 'LC' | 'NT' | 'VU' | 'EN' | 'CR' | 'DD';

export interface FishSpecies {
  id: string;
  name: string;
  scientificName: string;
  family: string;
  rarity: RarityTier;
  rarityLabel: string;
  xpBase: number;
  regions: Region[];
  habitat: Habitat[];
  averageWeightKg: number;
  maxWeightKg: number;
  worldRecordKg: number;
  worldRecordLocation: string;
  bestBaits: string[];
  bestSeasons: Season[];
  bestTimeOfDay: TimeOfDay[];
  diet: string[];
  description: string;
  funFact: string;
  conservationStatus: ConservationStatus;
  catchDifficulty: 1 | 2 | 3 | 4 | 5;
  minLegalSizeCm?: number;
  category: string;
}

export const RARITY_COLORS: Record<RarityTier, string> = {
  common: '#8B95A7',
  uncommon: '#4ADE80',
  rare: '#3B82F6',
  epic: '#A855F7',
  legendary: '#F59E0B',
};

export const RARITY_GLOW: Record<RarityTier, string> = {
  common: 'rgba(139,149,167,0.25)',
  uncommon: 'rgba(74,222,128,0.3)',
  rare: 'rgba(59,130,246,0.3)',
  epic: 'rgba(168,85,247,0.3)',
  legendary: 'rgba(245,158,11,0.4)',
};

export const RARITY_LABELS: Record<RarityTier, string> = {
  common: 'Common',
  uncommon: 'Uncommon',
  rare: 'Rare',
  epic: 'Epic',
  legendary: 'Legendary',
};

export const FISH_DATABASE: FishSpecies[] = [
  // ── COMMON ──
  {
    id: 'roach', name: 'Roach', scientificName: 'Rutilus rutilus', family: 'Cyprinidae',
    rarity: 'common', rarityLabel: 'Common', xpBase: 10,
    regions: ['UK', 'IE', 'EU'], habitat: ['river', 'lake', 'canal', 'reservoir'],
    averageWeightKg: 0.3, maxWeightKg: 1.8, worldRecordKg: 1.9, worldRecordLocation: 'River Stour, UK',
    bestBaits: ['Maggots', 'Bread', 'Corn', 'Hemp'],
    bestSeasons: ['spring', 'summer', 'autumn'], bestTimeOfDay: ['morning', 'afternoon'],
    diet: ['Insects', 'Plant matter', 'Small invertebrates'],
    description: "One of the UK's most widespread freshwater fish. Silver-bodied with red fins, roach are excellent for beginners and experienced anglers alike.",
    funFact: 'Roach can hybridise with bream and rudd, producing infertile offspring.',
    conservationStatus: 'LC', catchDifficulty: 1, minLegalSizeCm: 20, category: 'Coarse',
  },
  {
    id: 'perch', name: 'Perch', scientificName: 'Perca fluviatilis', family: 'Percidae',
    rarity: 'common', rarityLabel: 'Common', xpBase: 10,
    regions: ['UK', 'IE', 'EU'], habitat: ['river', 'lake', 'canal', 'reservoir'],
    averageWeightKg: 0.4, maxWeightKg: 3.5, worldRecordKg: 4.81, worldRecordLocation: 'Lake Hauroko, New Zealand',
    bestBaits: ['Worms', 'Maggots', 'Spinners', 'Small jigs'],
    bestSeasons: ['autumn', 'winter', 'spring'], bestTimeOfDay: ['dawn', 'dusk', 'morning'],
    diet: ['Small fish', 'Invertebrates', 'Worms'],
    description: 'Boldly striped with vivid green/black markings and bright red fins. A predatory species found across still and moving waters.',
    funFact: 'Perch hunt in packs, herding shoals of small fish to the surface.',
    conservationStatus: 'LC', catchDifficulty: 2, minLegalSizeCm: 23, category: 'Coarse',
  },
  {
    id: 'bream', name: 'Common Bream', scientificName: 'Abramis brama', family: 'Cyprinidae',
    rarity: 'common', rarityLabel: 'Common', xpBase: 10,
    regions: ['UK', 'IE', 'EU'], habitat: ['river', 'lake', 'canal', 'reservoir'],
    averageWeightKg: 1.5, maxWeightKg: 9.0, worldRecordKg: 9.1, worldRecordLocation: 'River Shannon, Ireland',
    bestBaits: ['Boilies', 'Corn', 'Maggots', 'Groundbait'],
    bestSeasons: ['summer', 'autumn'], bestTimeOfDay: ['dusk', 'night', 'dawn'],
    diet: ['Bloodworms', 'Invertebrates', 'Plant matter'],
    description: 'Deep-bodied, bronze-flanked fish that favour deep, slow-moving or still waters. An iconic UK specimen fish.',
    funFact: 'Bream roll at the surface in warm evenings, giving away their location.',
    conservationStatus: 'LC', catchDifficulty: 2, minLegalSizeCm: 30, category: 'Coarse',
  },
  {
    id: 'tench', name: 'Tench', scientificName: 'Tinca tinca', family: 'Cyprinidae',
    rarity: 'common', rarityLabel: 'Common', xpBase: 10,
    regions: ['UK', 'IE', 'EU'], habitat: ['lake', 'reservoir', 'canal'],
    averageWeightKg: 1.0, maxWeightKg: 7.0, worldRecordKg: 7.53, worldRecordLocation: 'UK',
    bestBaits: ['Corn', 'Bread', 'Maggots', 'Luncheon meat'],
    bestSeasons: ['summer', 'spring'], bestTimeOfDay: ['dawn', 'morning', 'dusk'],
    diet: ['Invertebrates', 'Molluscs', 'Plant matter'],
    description: "A beautiful green/olive fish with tiny scales and a distinctive orange eye. Known as the 'doctor fish' for its thick protective mucus.",
    funFact: "Other fish were thought to rub against tench to heal wounds — hence 'doctor fish'.",
    conservationStatus: 'LC', catchDifficulty: 2, minLegalSizeCm: 25, category: 'Coarse',
  },
  {
    id: 'gudgeon', name: 'Gudgeon', scientificName: 'Gobio gobio', family: 'Cyprinidae',
    rarity: 'common', rarityLabel: 'Common', xpBase: 10,
    regions: ['UK', 'IE', 'EU'], habitat: ['river', 'canal'],
    averageWeightKg: 0.05, maxWeightKg: 0.15, worldRecordKg: 0.18, worldRecordLocation: 'UK',
    bestBaits: ['Maggots', 'Worms', 'Bloodworms'],
    bestSeasons: ['spring', 'summer'], bestTimeOfDay: ['morning', 'afternoon'],
    diet: ['Small invertebrates', 'Crustaceans'],
    description: 'A small bottom-dwelling fish with distinctive barbels. A great species for beginners.',
    funFact: 'Gudgeon have two barbels used to find food on the riverbed.',
    conservationStatus: 'LC', catchDifficulty: 1, category: 'Coarse',
  },
  {
    id: 'bleak', name: 'Bleak', scientificName: 'Alburnus alburnus', family: 'Cyprinidae',
    rarity: 'common', rarityLabel: 'Common', xpBase: 10,
    regions: ['UK', 'EU'], habitat: ['river', 'canal'],
    averageWeightKg: 0.03, maxWeightKg: 0.1, worldRecordKg: 0.1, worldRecordLocation: 'UK',
    bestBaits: ['Maggots', 'Tiny flies', 'Bread crumb'],
    bestSeasons: ['summer', 'spring'], bestTimeOfDay: ['morning', 'afternoon'],
    diet: ['Insects', 'Plankton'],
    description: 'A slim, silvery shoal fish found in rivers and canals. Fast-moving surface feeders.',
    funFact: 'Bleak scales were once used to make artificial pearls.',
    conservationStatus: 'LC', catchDifficulty: 1, category: 'Coarse',
  },
  {
    id: 'whiting', name: 'Whiting', scientificName: 'Merlangius merlangus', family: 'Gadidae',
    rarity: 'common', rarityLabel: 'Common', xpBase: 10,
    regions: ['UK', 'IE', 'EU'], habitat: ['sea'],
    averageWeightKg: 0.4, maxWeightKg: 3.0, worldRecordKg: 2.98, worldRecordLocation: 'UK',
    bestBaits: ['Worms', 'Squid', 'Mussel', 'Fish strip'],
    bestSeasons: ['winter', 'autumn'], bestTimeOfDay: ['morning', 'afternoon', 'night'],
    diet: ['Small fish', 'Crustaceans', 'Worms'],
    description: 'A classic winter sea fishing species from UK beaches and piers. Whiting move inshore in large numbers as temperatures drop.',
    funFact: 'Whiting are opportunistic feeders that will eat almost any bait.',
    conservationStatus: 'LC', catchDifficulty: 1, category: 'Sea',
  },
  {
    id: 'mackerel', name: 'Atlantic Mackerel', scientificName: 'Scomber scombrus', family: 'Scombridae',
    rarity: 'common', rarityLabel: 'Common', xpBase: 10,
    regions: ['UK', 'IE', 'EU', 'US'], habitat: ['sea', 'ocean'],
    averageWeightKg: 0.4, maxWeightKg: 3.0, worldRecordKg: 3.0, worldRecordLocation: 'Vineyard Sound, Massachusetts, USA',
    bestBaits: ['Feathers', 'Spinners', 'Small lures'],
    bestSeasons: ['summer', 'spring'], bestTimeOfDay: ['morning', 'afternoon'],
    diet: ['Small fish', 'Crustaceans', 'Plankton'],
    description: 'A fast, beautifully marked fish that arrives in UK waters in summer. Excellent sport on light tackle and superb eating.',
    funFact: 'Mackerel must constantly swim to breathe — they cannot pump water over their gills.',
    conservationStatus: 'LC', catchDifficulty: 1, category: 'Sea',
  },
  {
    id: 'flounder', name: 'Flounder', scientificName: 'Platichthys flesus', family: 'Pleuronectidae',
    rarity: 'common', rarityLabel: 'Common', xpBase: 10,
    regions: ['UK', 'IE', 'EU'], habitat: ['estuary', 'sea'],
    averageWeightKg: 0.4, maxWeightKg: 2.0, worldRecordKg: 2.59, worldRecordLocation: 'UK',
    bestBaits: ['Ragworm', 'Lugworm', 'Small crabs', 'Shrimp'],
    bestSeasons: ['autumn', 'winter', 'spring'], bestTimeOfDay: ['morning', 'afternoon'],
    diet: ['Worms', 'Small crustaceans', 'Shrimp'],
    description: 'The most common flatfish in UK estuaries. Tolerant of very low salinity and found far up tidal rivers.',
    funFact: 'Flounder can survive in almost completely fresh water.',
    conservationStatus: 'LC', catchDifficulty: 1, category: 'Sea',
  },
  {
    id: 'largemouth-bass', name: 'Largemouth Bass', scientificName: 'Micropterus salmoides', family: 'Centrarchidae',
    rarity: 'common', rarityLabel: 'Common', xpBase: 10,
    regions: ['US', 'CA'], habitat: ['lake', 'reservoir', 'river'],
    averageWeightKg: 1.5, maxWeightKg: 10.0, worldRecordKg: 10.09, worldRecordLocation: 'Montgomery Lake, Georgia, USA',
    bestBaits: ['Plastic worms', 'Crankbaits', 'Jigs', 'Spinnerbaits', 'Frogs'],
    bestSeasons: ['spring', 'summer', 'autumn'], bestTimeOfDay: ['dawn', 'dusk', 'morning'],
    diet: ['Fish', 'Frogs', 'Crayfish', 'Insects'],
    description: "America's most popular sport fish. Largemouth bass are aggressive, powerful fighters found across the US in virtually every warm-water habitat.",
    funFact: 'Largemouth bass can consume prey up to 35% of their own body length.',
    conservationStatus: 'LC', catchDifficulty: 2, minLegalSizeCm: 30, category: 'Bass',
  },
  {
    id: 'channel-catfish', name: 'Channel Catfish', scientificName: 'Ictalurus punctatus', family: 'Ictaluridae',
    rarity: 'common', rarityLabel: 'Common', xpBase: 10,
    regions: ['US', 'CA'], habitat: ['river', 'lake', 'reservoir'],
    averageWeightKg: 2.0, maxWeightKg: 26.0, worldRecordKg: 26.08, worldRecordLocation: 'Santee-Cooper Reservoir, South Carolina, USA',
    bestBaits: ['Stinkbait', 'Nightcrawlers', 'Chicken liver', 'Dough balls'],
    bestSeasons: ['summer', 'spring'], bestTimeOfDay: ['night', 'dusk', 'dawn'],
    diet: ['Fish', 'Insects', 'Crustaceans', 'Plant matter'],
    description: "America's most widely distributed catfish. Uses whisker-like barbels to detect food in murky water.",
    funFact: 'Channel catfish have taste buds all over their body, not just in their mouth.',
    conservationStatus: 'LC', catchDifficulty: 2, minLegalSizeCm: 30, category: 'Catfish',
  },
  // ── UNCOMMON ──
  {
    id: 'carp-common', name: 'Common Carp', scientificName: 'Cyprinus carpio', family: 'Cyprinidae',
    rarity: 'uncommon', rarityLabel: 'Uncommon', xpBase: 25,
    regions: ['UK', 'IE', 'EU', 'US', 'AUS', 'GLOBAL'], habitat: ['lake', 'reservoir', 'river', 'canal'],
    averageWeightKg: 5.0, maxWeightKg: 45.0, worldRecordKg: 45.59, worldRecordLocation: 'Euro Aqua Lake, Hungary',
    bestBaits: ['Boilies', 'Corn', 'Bread', 'Tigers', 'Pellets'],
    bestSeasons: ['summer', 'spring', 'autumn'], bestTimeOfDay: ['dusk', 'night', 'dawn'],
    diet: ['Invertebrates', 'Plant seeds', 'Crustaceans'],
    description: 'The king of coarse fishing. Common carp are powerful, intelligent fish that provide challenging angling worldwide.',
    funFact: "Carp can live for over 40 years and remember anglers' rigs.",
    conservationStatus: 'VU', catchDifficulty: 3, minLegalSizeCm: 35, category: 'Carp',
  },
  {
    id: 'carp-mirror', name: 'Mirror Carp', scientificName: 'Cyprinus carpio (mirror)', family: 'Cyprinidae',
    rarity: 'uncommon', rarityLabel: 'Uncommon', xpBase: 30,
    regions: ['UK', 'IE', 'EU', 'US'], habitat: ['lake', 'reservoir'],
    averageWeightKg: 6.0, maxWeightKg: 40.0, worldRecordKg: 41.08, worldRecordLocation: 'Etang La Saussaie, France',
    bestBaits: ['Boilies', 'Pop-ups', 'Corn', 'Pellets'],
    bestSeasons: ['summer', 'spring'], bestTimeOfDay: ['dusk', 'night', 'dawn'],
    diet: ['Invertebrates', 'Plant seeds', 'Boilies'],
    description: 'A selectively bred variant of common carp with irregular, large mirror-like scales. Each fish has a unique scale pattern.',
    funFact: 'A famous UK mirror carp called "Two Tone" was caught hundreds of times over its life.',
    conservationStatus: 'VU', catchDifficulty: 3, minLegalSizeCm: 35, category: 'Carp',
  },
  {
    id: 'rudd', name: 'Rudd', scientificName: 'Scardinius erythrophthalmus', family: 'Cyprinidae',
    rarity: 'uncommon', rarityLabel: 'Uncommon', xpBase: 25,
    regions: ['UK', 'IE', 'EU'], habitat: ['lake', 'river', 'canal'],
    averageWeightKg: 0.3, maxWeightKg: 2.0, worldRecordKg: 2.09, worldRecordLocation: 'Ireland',
    bestBaits: ['Bread', 'Maggots', 'Corn', 'Flies'],
    bestSeasons: ['summer', 'spring'], bestTimeOfDay: ['morning', 'afternoon', 'dusk'],
    diet: ['Insects', 'Plant matter', 'Small invertebrates'],
    description: 'A beautiful golden-flanked fish with vivid red fins. Often confused with roach but has a distinctly upturned mouth.',
    funFact: 'Rudd are surface feeders — their upturned mouth allows them to sip insects from the surface.',
    conservationStatus: 'LC', catchDifficulty: 2, minLegalSizeCm: 20, category: 'Coarse',
  },
  {
    id: 'chub', name: 'Chub', scientificName: 'Squalius cephalus', family: 'Cyprinidae',
    rarity: 'uncommon', rarityLabel: 'Uncommon', xpBase: 25,
    regions: ['UK', 'EU'], habitat: ['river'],
    averageWeightKg: 0.8, maxWeightKg: 4.5, worldRecordKg: 4.5, worldRecordLocation: 'River Avon, UK',
    bestBaits: ['Cheese', 'Bread', 'Luncheon meat', 'Spinners', 'Flies'],
    bestSeasons: ['autumn', 'winter', 'summer'], bestTimeOfDay: ['morning', 'afternoon'],
    diet: ['Invertebrates', 'Small fish', 'Berries', 'Insects'],
    description: 'A wary, intelligent river fish with a large head and wide mouth. Opportunistic feeders that will eat almost anything.',
    funFact: 'Chub will eat anything from blackberries to small frogs.',
    conservationStatus: 'LC', catchDifficulty: 3, minLegalSizeCm: 25, category: 'Coarse',
  },
  {
    id: 'barbel', name: 'Barbel', scientificName: 'Barbus barbus', family: 'Cyprinidae',
    rarity: 'uncommon', rarityLabel: 'Uncommon', xpBase: 30,
    regions: ['UK', 'EU'], habitat: ['river'],
    averageWeightKg: 2.0, maxWeightKg: 9.0, worldRecordKg: 9.05, worldRecordLocation: 'River Cherwell, UK',
    bestBaits: ['Boilies', 'Hemp', 'Meat', 'Pellets', 'Cheese'],
    bestSeasons: ['summer', 'autumn'], bestTimeOfDay: ['dusk', 'night'],
    diet: ['Invertebrates', 'Crustaceans', 'Plant matter'],
    description: 'A powerful, torpedo-shaped river fish with four barbels around its mouth. Barbel fight incredibly hard and are prized by river anglers.',
    funFact: 'Barbel fight so hard they can be temporarily paralysed from exhaustion after capture.',
    conservationStatus: 'LC', catchDifficulty: 3, minLegalSizeCm: 30, category: 'Coarse',
  },
  {
    id: 'dace', name: 'Dace', scientificName: 'Leuciscus leuciscus', family: 'Cyprinidae',
    rarity: 'uncommon', rarityLabel: 'Uncommon', xpBase: 25,
    regions: ['UK', 'EU'], habitat: ['river'],
    averageWeightKg: 0.15, maxWeightKg: 0.6, worldRecordKg: 0.57, worldRecordLocation: 'Little Ouse, UK',
    bestBaits: ['Maggots', 'Flies', 'Tares'],
    bestSeasons: ['winter', 'spring'], bestTimeOfDay: ['morning', 'afternoon'],
    diet: ['Insects', 'Small invertebrates'],
    description: 'A slim, silver fish found in fast-flowing rivers. One of the first freshwater species to spawn in spring.',
    funFact: 'Dace are one of the first fish to spawn each year, sometimes in February.',
    conservationStatus: 'LC', catchDifficulty: 2, minLegalSizeCm: 20, category: 'Coarse',
  },
  {
    id: 'pollock', name: 'Pollock', scientificName: 'Pollachius pollachius', family: 'Gadidae',
    rarity: 'uncommon', rarityLabel: 'Uncommon', xpBase: 25,
    regions: ['UK', 'IE', 'EU'], habitat: ['sea', 'ocean'],
    averageWeightKg: 2.0, maxWeightKg: 12.0, worldRecordKg: 11.8, worldRecordLocation: 'Scotland',
    bestBaits: ['Shads', 'Jigs', 'Worms', 'Spinners', 'Feathers'],
    bestSeasons: ['autumn', 'winter', 'spring'], bestTimeOfDay: ['dawn', 'dusk'],
    diet: ['Small fish', 'Sand eels', 'Crustaceans'],
    description: 'A powerful green-backed predator of rocky reefs and wrecks. Pollock fight hard on lures.',
    funFact: 'Pollock have a pronounced underbite and a distinctive curved lateral line.',
    conservationStatus: 'LC', catchDifficulty: 3, minLegalSizeCm: 30, category: 'Sea',
  },
  {
    id: 'plaice', name: 'Plaice', scientificName: 'Pleuronectes platessa', family: 'Pleuronectidae',
    rarity: 'uncommon', rarityLabel: 'Uncommon', xpBase: 25,
    regions: ['UK', 'IE', 'EU'], habitat: ['sea'],
    averageWeightKg: 1.0, maxWeightKg: 5.0, worldRecordKg: 7.12, worldRecordLocation: 'Salcombe, UK',
    bestBaits: ['Ragworm', 'Lugworm', 'Mussel', 'Cockles'],
    bestSeasons: ['spring', 'summer', 'autumn'], bestTimeOfDay: ['morning', 'afternoon'],
    diet: ['Worms', 'Molluscs', 'Crustaceans'],
    description: 'A beautiful flatfish decorated with vivid orange spots. Prized UK sea fishing target and excellent eating.',
    funFact: 'Plaice have both eyes on the right side of their body.',
    conservationStatus: 'LC', catchDifficulty: 2, minLegalSizeCm: 27, category: 'Sea',
  },
  {
    id: 'ray-thornback', name: 'Thornback Ray', scientificName: 'Raja clavata', family: 'Rajidae',
    rarity: 'uncommon', rarityLabel: 'Uncommon', xpBase: 30,
    regions: ['UK', 'IE', 'EU'], habitat: ['sea'],
    averageWeightKg: 3.0, maxWeightKg: 18.0, worldRecordKg: 17.09, worldRecordLocation: 'UK',
    bestBaits: ['Peeler crab', 'Squid', 'Worms', 'Sandeels'],
    bestSeasons: ['spring', 'summer', 'autumn'], bestTimeOfDay: ['morning', 'afternoon'],
    diet: ['Crustaceans', 'Fish', 'Worms'],
    description: 'The most common ray species around UK coasts, with distinctive thorny spines across back and wings.',
    funFact: 'Rays have electroreceptors that detect weak electric fields produced by prey buried in sand.',
    conservationStatus: 'NT', catchDifficulty: 2, minLegalSizeCm: 45, category: 'Sea',
  },
  {
    id: 'smallmouth-bass', name: 'Smallmouth Bass', scientificName: 'Micropterus dolomieu', family: 'Centrarchidae',
    rarity: 'uncommon', rarityLabel: 'Uncommon', xpBase: 25,
    regions: ['US', 'CA'], habitat: ['river', 'lake'],
    averageWeightKg: 1.0, maxWeightKg: 5.4, worldRecordKg: 5.41, worldRecordLocation: 'Dale Hollow Lake, Kentucky, USA',
    bestBaits: ['Tubes', 'Jigs', 'Crayfish imitations', 'Small spinners'],
    bestSeasons: ['spring', 'summer', 'autumn'], bestTimeOfDay: ['dawn', 'dusk'],
    diet: ['Crayfish', 'Small fish', 'Insects'],
    description: 'Pound for pound the hardest-fighting freshwater fish in North America. Found in clear, rocky rivers and lakes.',
    funFact: 'Smallmouth bass males guard the nest and eggs after spawning, fanning them with their tails.',
    conservationStatus: 'LC', catchDifficulty: 3, minLegalSizeCm: 30, category: 'Bass',
  },
  {
    id: 'walleye', name: 'Walleye', scientificName: 'Sander vitreus', family: 'Percidae',
    rarity: 'uncommon', rarityLabel: 'Uncommon', xpBase: 25,
    regions: ['US', 'CA'], habitat: ['lake', 'river'],
    averageWeightKg: 1.5, maxWeightKg: 11.3, worldRecordKg: 11.34, worldRecordLocation: 'Old Hickory Lake, Tennessee, USA',
    bestBaits: ['Jigs', 'Minnows', 'Crankbaits', 'Jigging spoons'],
    bestSeasons: ['spring', 'autumn', 'winter'], bestTimeOfDay: ['dusk', 'night', 'dawn'],
    diet: ['Fish', 'Crayfish', 'Insects'],
    description: 'The most popular eating fish in North America. Identified by large glassy eyes, prized for delicate white flesh.',
    funFact: 'Walleye eyes contain a special reflective layer that makes them glow in the dark.',
    conservationStatus: 'LC', catchDifficulty: 3, minLegalSizeCm: 38, category: 'Predator',
  },
  {
    id: 'black-seabream', name: 'Black Sea Bream', scientificName: 'Spondyliosoma cantharus', family: 'Sparidae',
    rarity: 'uncommon', rarityLabel: 'Uncommon', xpBase: 25,
    regions: ['UK', 'EU'], habitat: ['sea'],
    averageWeightKg: 1.0, maxWeightKg: 5.0, worldRecordKg: 4.85, worldRecordLocation: 'UK',
    bestBaits: ['Ragworm', 'Crab', 'Squid', 'Fish strips'],
    bestSeasons: ['summer', 'spring'], bestTimeOfDay: ['morning', 'afternoon'],
    diet: ['Crustaceans', 'Worms', 'Small fish'],
    description: 'A handsome silver-blue sea bream found along UK south and southwest coasts in summer.',
    funFact: 'Male black sea bream turn nearly black during breeding season to attract females.',
    conservationStatus: 'LC', catchDifficulty: 2, minLegalSizeCm: 23, category: 'Sea',
  },
  {
    id: 'golden-perch', name: 'Golden Perch', scientificName: 'Macquaria ambigua', family: 'Percichthyidae',
    rarity: 'uncommon', rarityLabel: 'Uncommon', xpBase: 25,
    regions: ['AUS'], habitat: ['river', 'lake'],
    averageWeightKg: 1.5, maxWeightKg: 23.0, worldRecordKg: 23.0, worldRecordLocation: 'Lake Mulwala, Australia',
    bestBaits: ['Lures', 'Yabbies', 'Worms', 'Spinners'],
    bestSeasons: ['spring', 'summer'], bestTimeOfDay: ['dusk', 'dawn'],
    diet: ['Yabbies', 'Fish', 'Insects'],
    description: 'A striking yellow-gold fish endemic to the Murray-Darling basin. Popular targets for both lure and bait anglers.',
    funFact: 'Golden perch can migrate hundreds of kilometres upstream to spawn after flood events.',
    conservationStatus: 'LC', catchDifficulty: 2, minLegalSizeCm: 30, category: 'Coarse',
  },
  {
    id: 'redfish', name: 'Red Drum (Redfish)', scientificName: 'Sciaenops ocellatus', family: 'Sciaenidae',
    rarity: 'uncommon', rarityLabel: 'Uncommon', xpBase: 30,
    regions: ['US'], habitat: ['sea', 'estuary'],
    averageWeightKg: 3.0, maxWeightKg: 42.0, worldRecordKg: 42.69, worldRecordLocation: 'Avon, North Carolina, USA',
    bestBaits: ['Gold spoons', 'Soft plastics', 'Crab', 'Shrimp'],
    bestSeasons: ['autumn', 'summer'], bestTimeOfDay: ['dawn', 'dusk'],
    diet: ['Crustaceans', 'Fish', 'Molluscs'],
    description: "The iconic inshore species of the Gulf Coast and Southeast. Identified by copper colour and distinctive black spot near tail.",
    funFact: "Red drum 'drum' by vibrating their swim bladder — that's the thumping sound after landing one.",
    conservationStatus: 'LC', catchDifficulty: 2, minLegalSizeCm: 45, category: 'Sea',
  },
  {
    id: 'northern-pike', name: 'Northern Pike', scientificName: 'Esox lucius', family: 'Esocidae',
    rarity: 'uncommon', rarityLabel: 'Uncommon', xpBase: 30,
    regions: ['US', 'CA'], habitat: ['lake', 'river'],
    averageWeightKg: 2.0, maxWeightKg: 25.0, worldRecordKg: 25.0, worldRecordLocation: 'Germany',
    bestBaits: ['Large lures', 'Spoons', 'Jerkbaits', 'Deadbaits'],
    bestSeasons: ['winter', 'spring', 'autumn'], bestTimeOfDay: ['dawn', 'dusk'],
    diet: ['Fish', 'Frogs', 'Small mammals', 'Ducks'],
    description: 'The apex predator of northern freshwater. Northern pike ambush prey from weed beds with explosive speed.',
    funFact: 'Pike have 700 teeth in multiple rows. When a tooth falls out, another grows to replace it.',
    conservationStatus: 'LC', catchDifficulty: 3, minLegalSizeCm: 50, category: 'Predator',
  },
  // ── RARE ──
  {
    id: 'pike', name: 'Pike (Specimen)', scientificName: 'Esox lucius', family: 'Esocidae',
    rarity: 'rare', rarityLabel: 'Rare', xpBase: 60,
    regions: ['UK', 'IE', 'EU'], habitat: ['lake', 'river', 'reservoir', 'canal'],
    averageWeightKg: 3.0, maxWeightKg: 25.0, worldRecordKg: 25.0, worldRecordLocation: 'Germany',
    bestBaits: ['Deadbaits', 'Large lures', 'Spinners', 'Livebait'],
    bestSeasons: ['winter', 'autumn', 'spring'], bestTimeOfDay: ['dawn', 'dusk', 'morning'],
    diet: ['Fish', 'Ducks', 'Frogs', 'Small mammals'],
    description: 'The apex predator of UK freshwater. Pike have fearsome teeth and ambush prey with explosive speed. A legendary species.',
    funFact: 'Pike have been recorded eating ducks, muskrats, and even juvenile otters.',
    conservationStatus: 'LC', catchDifficulty: 3, minLegalSizeCm: 50, category: 'Predator',
  },
  {
    id: 'zander', name: 'Zander', scientificName: 'Sander lucioperca', family: 'Percidae',
    rarity: 'rare', rarityLabel: 'Rare', xpBase: 60,
    regions: ['UK', 'EU'], habitat: ['river', 'lake', 'canal'],
    averageWeightKg: 2.0, maxWeightKg: 12.0, worldRecordKg: 11.35, worldRecordLocation: 'Sweden',
    bestBaits: ['Deadbaits', 'Soft plastic lures', 'Jigs'],
    bestSeasons: ['autumn', 'winter'], bestTimeOfDay: ['dusk', 'night', 'dawn'],
    diet: ['Fish', 'Perch', 'Roach'],
    description: 'A pike-perch originating from Eastern Europe. Zander have exceptional night vision and hunt in murky waters.',
    funFact: 'Zander have a reflective layer in their eyes that helps them hunt in near-darkness.',
    conservationStatus: 'LC', catchDifficulty: 4, minLegalSizeCm: 45, category: 'Predator',
  },
  {
    id: 'catfish-wels', name: 'Wels Catfish', scientificName: 'Silurus glanis', family: 'Siluridae',
    rarity: 'rare', rarityLabel: 'Rare', xpBase: 80,
    regions: ['UK', 'EU'], habitat: ['lake', 'river'],
    averageWeightKg: 20.0, maxWeightKg: 130.0, worldRecordKg: 130.0, worldRecordLocation: 'River Ebro, Spain',
    bestBaits: ['Deadbaits', 'Liver', 'Pellets', 'Large lures'],
    bestSeasons: ['summer', 'autumn'], bestTimeOfDay: ['night', 'dusk'],
    diet: ['Fish', 'Waterfowl', 'Amphibians'],
    description: "Europe's largest freshwater fish. Wels catfish are nocturnal predators that can grow to enormous sizes in warm European waters.",
    funFact: 'Wels catfish have been documented beaching themselves to catch pigeons on the River Tarn in France.',
    conservationStatus: 'LC', catchDifficulty: 4, category: 'Predator',
  },
  {
    id: 'trout-brown', name: 'Brown Trout', scientificName: 'Salmo trutta', family: 'Salmonidae',
    rarity: 'rare', rarityLabel: 'Rare', xpBase: 60,
    regions: ['UK', 'IE', 'EU', 'US', 'CA', 'AUS', 'NZ'], habitat: ['river', 'lake'],
    averageWeightKg: 1.0, maxWeightKg: 20.0, worldRecordKg: 19.1, worldRecordLocation: 'Arkansas River, USA',
    bestBaits: ['Flies', 'Worms', 'Spinners', 'Small lures'],
    bestSeasons: ['spring', 'summer', 'autumn'], bestTimeOfDay: ['dawn', 'dusk', 'morning'],
    diet: ['Insects', 'Small fish', 'Crustaceans'],
    description: 'A beautiful spotted trout found in cold, clean rivers and lakes. The quintessential fly fishing species — fights magnificently.',
    funFact: 'Brown trout can detect vibrations through their lateral line from 30 feet away.',
    conservationStatus: 'LC', catchDifficulty: 4, minLegalSizeCm: 30, category: 'Game',
  },
  {
    id: 'trout-rainbow', name: 'Rainbow Trout', scientificName: 'Oncorhynchus mykiss', family: 'Salmonidae',
    rarity: 'rare', rarityLabel: 'Rare', xpBase: 40,
    regions: ['UK', 'IE', 'EU', 'US', 'CA', 'AUS', 'NZ', 'GLOBAL'], habitat: ['river', 'lake', 'reservoir'],
    averageWeightKg: 1.5, maxWeightKg: 25.0, worldRecordKg: 21.77, worldRecordLocation: 'Bell Island, Alaska',
    bestBaits: ['Flies', 'Lures', 'Spinners', 'PowerBait', 'Worms'],
    bestSeasons: ['spring', 'autumn', 'winter'], bestTimeOfDay: ['dawn', 'dusk', 'morning'],
    diet: ['Insects', 'Small fish', 'Crustaceans'],
    description: 'Introduced worldwide from its native Pacific coast. Rainbow trout are famous for their acrobatic leaps when hooked.',
    funFact: 'Rainbow trout can jump up to 3 metres in the air when hooked.',
    conservationStatus: 'LC', catchDifficulty: 3, minLegalSizeCm: 30, category: 'Game',
  },
  {
    id: 'grayling', name: 'Grayling', scientificName: 'Thymallus thymallus', family: 'Salmonidae',
    rarity: 'rare', rarityLabel: 'Rare', xpBase: 60,
    regions: ['UK', 'EU'], habitat: ['river'],
    averageWeightKg: 0.5, maxWeightKg: 3.0, worldRecordKg: 2.7, worldRecordLocation: 'River Test, UK',
    bestBaits: ['Flies', 'Maggots', 'Nymphs'],
    bestSeasons: ['autumn', 'winter'], bestTimeOfDay: ['morning', 'afternoon'],
    diet: ['Insects', 'Nymphs', 'Small invertebrates'],
    description: 'A beautiful sail-finned fish of clear chalk streams. Has a distinctive large dorsal fin and smells faintly of thyme.',
    funFact: "Grayling are nicknamed 'the lady of the stream' and emit a faint thyme-like odour.",
    conservationStatus: 'LC', catchDifficulty: 4, minLegalSizeCm: 25, category: 'Game',
  },
  {
    id: 'bass', name: 'Sea Bass', scientificName: 'Dicentrarchus labrax', family: 'Moronidae',
    rarity: 'rare', rarityLabel: 'Rare', xpBase: 60,
    regions: ['UK', 'IE', 'EU'], habitat: ['sea', 'estuary'],
    averageWeightKg: 2.0, maxWeightKg: 12.0, worldRecordKg: 12.09, worldRecordLocation: "Sables d'Olonne, France",
    bestBaits: ['Lures', 'Plugs', 'Worms', 'Crab', 'Sand eels'],
    bestSeasons: ['summer', 'autumn', 'spring'], bestTimeOfDay: ['dawn', 'dusk', 'night'],
    diet: ['Small fish', 'Crustaceans', 'Sand eels'],
    description: "The sea angler's ultimate prize. Bass are powerful, hard-fighting fish that prowl surf beaches, rocky headlands, and estuaries.",
    funFact: 'Bass have been clocked swimming at over 20mph in pursuit of prey.',
    conservationStatus: 'LC', catchDifficulty: 4, minLegalSizeCm: 42, category: 'Sea',
  },
  {
    id: 'cod', name: 'Atlantic Cod', scientificName: 'Gadus morhua', family: 'Gadidae',
    rarity: 'rare', rarityLabel: 'Rare', xpBase: 60,
    regions: ['UK', 'IE', 'EU', 'US', 'CA'], habitat: ['sea', 'ocean'],
    averageWeightKg: 5.0, maxWeightKg: 90.0, worldRecordKg: 98.95, worldRecordLocation: 'Isle of Shoals, New Hampshire, USA',
    bestBaits: ['Squid', 'Mackerel', 'Worms', 'Peeler crab'],
    bestSeasons: ['winter', 'autumn'], bestTimeOfDay: ['morning', 'afternoon'],
    diet: ['Fish', 'Crustaceans', 'Molluscs'],
    description: 'Once the most plentiful fish in the North Atlantic. A classic UK sea fishing target, especially in winter.',
    funFact: 'Cod have a chin barbel (single whisker) that helps them detect food on the seabed.',
    conservationStatus: 'VU', catchDifficulty: 3, minLegalSizeCm: 35, category: 'Sea',
  },
  {
    id: 'mullet', name: 'Thick-lipped Mullet', scientificName: 'Chelon labrosus', family: 'Mugilidae',
    rarity: 'rare', rarityLabel: 'Rare', xpBase: 80,
    regions: ['UK', 'IE', 'EU'], habitat: ['estuary', 'sea'],
    averageWeightKg: 1.5, maxWeightKg: 8.0, worldRecordKg: 8.0, worldRecordLocation: 'UK',
    bestBaits: ['Bread', 'Ragworm', 'Maggots', 'Mackerel offal'],
    bestSeasons: ['summer', 'spring'], bestTimeOfDay: ['morning', 'afternoon'],
    diet: ['Algae', 'Small invertebrates', 'Organic material'],
    description: 'The ultimate challenge for UK shore anglers. Mullet are notoriously wary and selective, often swimming past bait without taking it.',
    funFact: "Mullet will follow fishing boats and sewage outfalls — they're less picky when the food is right.",
    conservationStatus: 'LC', catchDifficulty: 5, minLegalSizeCm: 35, category: 'Sea',
  },
  {
    id: 'sole', name: 'Dover Sole', scientificName: 'Solea solea', family: 'Soleidae',
    rarity: 'rare', rarityLabel: 'Rare', xpBase: 60,
    regions: ['UK', 'IE', 'EU'], habitat: ['sea'],
    averageWeightKg: 0.4, maxWeightKg: 2.0, worldRecordKg: 2.5, worldRecordLocation: 'UK',
    bestBaits: ['Ragworm', 'Squid strip', 'Shellfish'],
    bestSeasons: ['summer', 'autumn'], bestTimeOfDay: ['night', 'dusk'],
    diet: ['Worms', 'Molluscs', 'Crustaceans'],
    description: 'A highly prized flatfish that favours sandy beaches after dark. Considered one of the finest eating fish.',
    funFact: 'Sole use UV detection to find worms in sand at night.',
    conservationStatus: 'LC', catchDifficulty: 3, minLegalSizeCm: 24, category: 'Sea',
  },
  {
    id: 'spurdog', name: 'Spurdog', scientificName: 'Squalus acanthias', family: 'Squalidae',
    rarity: 'rare', rarityLabel: 'Rare', xpBase: 60,
    regions: ['UK', 'IE', 'EU', 'US', 'CA'], habitat: ['sea', 'ocean'],
    averageWeightKg: 4.0, maxWeightKg: 10.0, worldRecordKg: 9.0, worldRecordLocation: 'UK',
    bestBaits: ['Mackerel', 'Herring', 'Squid'],
    bestSeasons: ['winter', 'autumn'], bestTimeOfDay: ['morning', 'afternoon'],
    diet: ['Fish', 'Squid', 'Crustaceans'],
    description: 'A small shark with two venomous spines. Spurdog travel in large packs and were once hugely abundant in UK waters.',
    funFact: 'Spurdog have a gestation period of 22-24 months — the longest of any vertebrate.',
    conservationStatus: 'VU', catchDifficulty: 2, minLegalSizeCm: 100, category: 'Sea',
  },
  {
    id: 'smoothound', name: 'Smoothound', scientificName: 'Mustelus mustelus', family: 'Triakidae',
    rarity: 'rare', rarityLabel: 'Rare', xpBase: 60,
    regions: ['UK', 'IE', 'EU'], habitat: ['sea'],
    averageWeightKg: 4.0, maxWeightKg: 12.0, worldRecordKg: 13.15, worldRecordLocation: 'UK',
    bestBaits: ['Peeler crab', 'Hermit crab', 'Squid'],
    bestSeasons: ['summer', 'spring'], bestTimeOfDay: ['morning', 'afternoon'],
    diet: ['Crustaceans', 'Molluscs', 'Small fish'],
    description: 'A powerful, fast-moving shark providing spectacular sport from UK beaches and boats in summer.',
    funFact: 'Smoothhounds have blunt, crushing teeth specially adapted for eating crabs.',
    conservationStatus: 'VU', catchDifficulty: 3, minLegalSizeCm: 75, category: 'Sea',
  },
  {
    id: 'blue-catfish', name: 'Blue Catfish', scientificName: 'Ictalurus furcatus', family: 'Ictaluridae',
    rarity: 'rare', rarityLabel: 'Rare', xpBase: 80,
    regions: ['US'], habitat: ['river', 'reservoir'],
    averageWeightKg: 8.0, maxWeightKg: 68.0, worldRecordKg: 68.04, worldRecordLocation: 'Kerr Lake, Virginia, USA',
    bestBaits: ['Cut shad', 'Skipjack', 'Live bait', 'Punch bait'],
    bestSeasons: ['summer', 'spring', 'autumn'], bestTimeOfDay: ['night', 'dusk'],
    diet: ['Fish', 'Mussels', 'Crayfish'],
    description: 'The largest North American catfish. Blue catfish can reach enormous sizes in large river systems.',
    funFact: 'The current world record blue catfish weighed 143 pounds.',
    conservationStatus: 'LC', catchDifficulty: 3, category: 'Catfish',
  },
  {
    id: 'striped-bass', name: 'Striped Bass', scientificName: 'Morone saxatilis', family: 'Moronidae',
    rarity: 'rare', rarityLabel: 'Rare', xpBase: 60,
    regions: ['US'], habitat: ['sea', 'river', 'estuary'],
    averageWeightKg: 4.0, maxWeightKg: 36.0, worldRecordKg: 35.6, worldRecordLocation: 'Westbrook, Connecticut, USA',
    bestBaits: ['Bunker', 'Eels', 'Topwater lures', 'Bucktails'],
    bestSeasons: ['spring', 'autumn'], bestTimeOfDay: ['dawn', 'dusk', 'night'],
    diet: ['Fish', 'Squid', 'Crustaceans'],
    description: 'The iconic sport fish of the US East Coast. Striped bass migrate seasonally, drawing massive angling followings.',
    funFact: 'Striped bass can live up to 30 years and females grow much larger than males.',
    conservationStatus: 'LC', catchDifficulty: 3, minLegalSizeCm: 71, category: 'Bass',
  },
  {
    id: 'barramundi', name: 'Barramundi', scientificName: 'Lates calcarifer', family: 'Latidae',
    rarity: 'rare', rarityLabel: 'Rare', xpBase: 80,
    regions: ['AUS'], habitat: ['river', 'estuary', 'sea'],
    averageWeightKg: 4.0, maxWeightKg: 60.0, worldRecordKg: 44.0, worldRecordLocation: 'Daly River, Northern Territory, Australia',
    bestBaits: ['Lures', 'Mullet', 'Prawns', 'Threadfin'],
    bestSeasons: ['summer', 'autumn'], bestTimeOfDay: ['dawn', 'dusk', 'night'],
    diet: ['Fish', 'Crustaceans', 'Frogs'],
    description: "Australia's premier sport and eating fish. Barramundi are powerful, acrobatic fighters.",
    funFact: 'All barramundi are born male and some change to female as they grow older.',
    conservationStatus: 'LC', catchDifficulty: 3, minLegalSizeCm: 55, category: 'Sea',
  },
  {
    id: 'snook', name: 'Common Snook', scientificName: 'Centropomus undecimalis', family: 'Centropomidae',
    rarity: 'rare', rarityLabel: 'Rare', xpBase: 60,
    regions: ['US'], habitat: ['sea', 'estuary', 'river'],
    averageWeightKg: 3.0, maxWeightKg: 24.0, worldRecordKg: 24.32, worldRecordLocation: 'Parismina Ranch, Costa Rica',
    bestBaits: ['Live shrimp', 'Pilchards', 'Jerkbaits', 'Flies'],
    bestSeasons: ['summer', 'spring'], bestTimeOfDay: ['dawn', 'dusk', 'night'],
    diet: ['Fish', 'Shrimp', 'Crabs'],
    description: "Florida's most prized inshore game fish. Snook lurk around docks, bridges, and mangroves, ambushing baitfish.",
    funFact: 'Snook are sensitive to cold temperatures and die if water drops below 60 F.',
    conservationStatus: 'LC', catchDifficulty: 3, minLegalSizeCm: 71, category: 'Sea',
  },
  {
    id: 'mahi-mahi', name: 'Mahi-Mahi', scientificName: 'Coryphaena hippurus', family: 'Coryphaenidae',
    rarity: 'rare', rarityLabel: 'Rare', xpBase: 80,
    regions: ['US', 'AUS', 'GLOBAL'], habitat: ['ocean'],
    averageWeightKg: 6.0, maxWeightKg: 40.0, worldRecordKg: 39.46, worldRecordLocation: 'Papagallo Gulf, Costa Rica',
    bestBaits: ['Flying fish', 'Squid', 'Lures', 'Live bait'],
    bestSeasons: ['summer', 'spring'], bestTimeOfDay: ['morning', 'afternoon'],
    diet: ['Flying fish', 'Squid', 'Small fish'],
    description: 'A spectacularly coloured fish of tropical and subtropical seas. Among the most beautiful fish in the ocean.',
    funFact: 'Mahi-mahi can grow from 1 to 30 inches in just a few months — one of the fastest-growing fish.',
    conservationStatus: 'LC', catchDifficulty: 3, category: 'Big Game',
  },
  {
    id: 'yellowtail-sa', name: 'Cape Yellowtail', scientificName: 'Seriola lalandi', family: 'Carangidae',
    rarity: 'rare', rarityLabel: 'Rare', xpBase: 80,
    regions: ['ZA', 'AUS'], habitat: ['sea', 'ocean'],
    averageWeightKg: 5.0, maxWeightKg: 50.0, worldRecordKg: 52.1, worldRecordLocation: 'Alijos Rocks, Mexico',
    bestBaits: ['Lures', 'Squid', 'Live bait', 'Jigs'],
    bestSeasons: ['autumn', 'winter'], bestTimeOfDay: ['morning', 'afternoon'],
    diet: ['Fish', 'Squid', 'Crustaceans'],
    description: "South Africa's most coveted inshore game fish. Yellowtail run along the Cape coast in winter.",
    funFact: 'Yellowtail are also called kingfish and are an amberjack species.',
    conservationStatus: 'LC', catchDifficulty: 3, category: 'Sea',
  },
  // ── EPIC ──
  {
    id: 'salmon-atlantic', name: 'Atlantic Salmon', scientificName: 'Salmo salar', family: 'Salmonidae',
    rarity: 'epic', rarityLabel: 'Epic', xpBase: 150,
    regions: ['UK', 'IE', 'EU', 'US', 'CA'], habitat: ['river', 'ocean'],
    averageWeightKg: 4.0, maxWeightKg: 35.0, worldRecordKg: 35.89, worldRecordLocation: 'River Tay, Scotland',
    bestBaits: ['Flies', 'Spinners', 'Prawns', 'Worms'],
    bestSeasons: ['spring', 'summer', 'autumn'], bestTimeOfDay: ['dawn', 'dusk', 'morning'],
    diet: ['Marine fish', 'Crustaceans', 'Squid'],
    description: 'The king of the river. Atlantic salmon migrate thousands of miles from ocean feeding grounds back to their birth rivers to spawn. Catching one is a lifetime achievement.',
    funFact: 'Salmon return to the exact river where they were born using magnetic field detection and smell.',
    conservationStatus: 'VU', catchDifficulty: 5, minLegalSizeCm: 45, category: 'Game',
  },
  {
    id: 'sea-trout', name: 'Sea Trout', scientificName: 'Salmo trutta trutta', family: 'Salmonidae',
    rarity: 'epic', rarityLabel: 'Epic', xpBase: 150,
    regions: ['UK', 'IE', 'EU'], habitat: ['river', 'sea'],
    averageWeightKg: 2.0, maxWeightKg: 15.0, worldRecordKg: 16.0, worldRecordLocation: 'Soca River, Slovenia',
    bestBaits: ['Flies', 'Spinners', 'Worms', 'Sand eels'],
    bestSeasons: ['summer', 'autumn'], bestTimeOfDay: ['night', 'dusk', 'dawn'],
    diet: ['Fish', 'Crustaceans', 'Insects'],
    description: 'The migratory form of brown trout. Sea trout are renowned night feeders and provide incredible sport.',
    funFact: 'Sea trout are night feeders and are best caught in complete darkness.',
    conservationStatus: 'LC', catchDifficulty: 5, minLegalSizeCm: 40, category: 'Game',
  },
  {
    id: 'conger-eel', name: 'Conger Eel', scientificName: 'Conger conger', family: 'Congridae',
    rarity: 'epic', rarityLabel: 'Epic', xpBase: 150,
    regions: ['UK', 'IE', 'EU'], habitat: ['sea', 'ocean'],
    averageWeightKg: 20.0, maxWeightKg: 110.0, worldRecordKg: 133.4, worldRecordLocation: 'Eddystone Rocks, Plymouth, UK',
    bestBaits: ['Mackerel head', 'Squid', 'Cuttlefish', 'Crab'],
    bestSeasons: ['summer', 'autumn'], bestTimeOfDay: ['night', 'dusk'],
    diet: ['Fish', 'Crustaceans', 'Octopus'],
    description: 'The sea monster of UK waters. Conger eels lurk in wrecks and rock crevices, growing to enormous proportions.',
    funFact: 'Conger eels die after spawning and only breed once in their entire lifetime.',
    conservationStatus: 'DD', catchDifficulty: 5, category: 'Sea',
  },
  {
    id: 'tope', name: 'Tope Shark', scientificName: 'Galeorhinus galeus', family: 'Triakidae',
    rarity: 'epic', rarityLabel: 'Epic', xpBase: 150,
    regions: ['UK', 'IE', 'EU'], habitat: ['sea', 'ocean'],
    averageWeightKg: 12.0, maxWeightKg: 45.0, worldRecordKg: 45.36, worldRecordLocation: 'Parengarenga Harbour, NZ',
    bestBaits: ['Mackerel', 'Herring', 'Squid'],
    bestSeasons: ['summer', 'spring'], bestTimeOfDay: ['morning', 'afternoon'],
    diet: ['Fish', 'Squid', 'Crustaceans'],
    description: "The UK's most commonly caught shark. Tope are slender, fast, and fight incredibly hard. A true catch-and-release species.",
    funFact: 'Tope sharks can live for 55 years and have complex family social structures.',
    conservationStatus: 'VU', catchDifficulty: 4, category: 'Sea',
  },
  {
    id: 'turbot', name: 'Turbot', scientificName: 'Scophthalmus maximus', family: 'Scophthalmidae',
    rarity: 'epic', rarityLabel: 'Epic', xpBase: 150,
    regions: ['UK', 'IE', 'EU'], habitat: ['sea'],
    averageWeightKg: 4.0, maxWeightKg: 25.0, worldRecordKg: 25.0, worldRecordLocation: 'Dunbar, Scotland',
    bestBaits: ['Sand eels', 'Peeler crab', 'Squid', 'Lures'],
    bestSeasons: ['summer', 'spring'], bestTimeOfDay: ['morning', 'afternoon'],
    diet: ['Small fish', 'Sand eels', 'Crustaceans'],
    description: 'The diamond of the flatfishes. Turbot are powerful, hard-fighting fish extremely prized by boat anglers.',
    funFact: 'Turbot are ambush predators that bury themselves in sand with only their eyes exposed.',
    conservationStatus: 'LC', catchDifficulty: 4, minLegalSizeCm: 30, category: 'Sea',
  },
  {
    id: 'murray-cod', name: 'Murray Cod', scientificName: 'Maccullochella peelii', family: 'Percichthyidae',
    rarity: 'epic', rarityLabel: 'Epic', xpBase: 150,
    regions: ['AUS'], habitat: ['river', 'lake'],
    averageWeightKg: 10.0, maxWeightKg: 113.5, worldRecordKg: 113.5, worldRecordLocation: 'Murray-Darling Basin, Australia',
    bestBaits: ['Large lures', 'Surface lures', 'Crayfish', 'Large jigs'],
    bestSeasons: ['spring', 'summer'], bestTimeOfDay: ['dusk', 'night', 'dawn'],
    diet: ['Fish', 'Crayfish', 'Frogs', 'Ducks'],
    description: "Australia's largest freshwater fish and a national icon. Murray cod are slow-growing, long-lived predators.",
    funFact: 'Murray cod can live for over 100 years.',
    conservationStatus: 'VU', catchDifficulty: 4, minLegalSizeCm: 55, category: 'Predator',
  },
  {
    id: 'carp-leather', name: 'Leather Carp', scientificName: 'Cyprinus carpio (leather)', family: 'Cyprinidae',
    rarity: 'epic', rarityLabel: 'Epic', xpBase: 150,
    regions: ['UK', 'EU'], habitat: ['lake', 'reservoir'],
    averageWeightKg: 5.0, maxWeightKg: 35.0, worldRecordKg: 36.5, worldRecordLocation: 'France',
    bestBaits: ['Boilies', 'Pop-ups', 'Corn'],
    bestSeasons: ['summer', 'spring'], bestTimeOfDay: ['night', 'dawn', 'dusk'],
    diet: ['Invertebrates', 'Plant seeds'],
    description: 'Nearly scale-free variant of carp with smooth, leather-like skin. Extremely rare and highly sought after.',
    funFact: 'Leather carp can be almost completely scale-free, giving them a unique smooth appearance.',
    conservationStatus: 'VU', catchDifficulty: 4, minLegalSizeCm: 35, category: 'Carp',
  },
  {
    id: 'wahoo', name: 'Wahoo', scientificName: 'Acanthocybium solandri', family: 'Scombridae',
    rarity: 'epic', rarityLabel: 'Epic', xpBase: 150,
    regions: ['US', 'AUS', 'GLOBAL'], habitat: ['ocean'],
    averageWeightKg: 20.0, maxWeightKg: 83.0, worldRecordKg: 83.46, worldRecordLocation: 'Cabo San Lucas, Mexico',
    bestBaits: ['High-speed lures', 'Rigged baits', 'Wahoo bombs'],
    bestSeasons: ['summer', 'autumn'], bestTimeOfDay: ['morning', 'afternoon'],
    diet: ['Fish', 'Squid'],
    description: 'One of the fastest ocean fish. Wahoo are slender, beautifully coloured and have razor-sharp teeth.',
    funFact: 'Wahoo can reach 77 km/h and are one of the fastest fish in tropical waters.',
    conservationStatus: 'LC', catchDifficulty: 4, category: 'Big Game',
  },
  {
    id: 'yellowfin-tuna', name: 'Yellowfin Tuna', scientificName: 'Thunnus albacares', family: 'Scombridae',
    rarity: 'epic', rarityLabel: 'Epic', xpBase: 150,
    regions: ['US', 'AUS', 'GLOBAL'], habitat: ['ocean'],
    averageWeightKg: 40.0, maxWeightKg: 200.0, worldRecordKg: 176.35, worldRecordLocation: 'Cabo San Lucas, Mexico',
    bestBaits: ['Lures', 'Poppers', 'Jigs', 'Live bait'],
    bestSeasons: ['summer', 'autumn'], bestTimeOfDay: ['morning', 'afternoon'],
    diet: ['Fish', 'Squid', 'Crustaceans'],
    description: 'A powerful, fast tuna species found in tropical and subtropical waters. Extraordinary fighters capable of long, unstoppable runs.',
    funFact: 'Yellowfin tuna can maintain a core body temperature above the surrounding water temperature.',
    conservationStatus: 'NT', catchDifficulty: 4, category: 'Big Game',
  },
  {
    id: 'eel', name: 'European Eel', scientificName: 'Anguilla anguilla', family: 'Anguillidae',
    rarity: 'epic', rarityLabel: 'Epic', xpBase: 150,
    regions: ['UK', 'IE', 'EU'], habitat: ['river', 'lake', 'canal', 'estuary'],
    averageWeightKg: 0.5, maxWeightKg: 5.0, worldRecordKg: 5.05, worldRecordLocation: 'Denmark',
    bestBaits: ['Worms', 'Fish strip', 'Dead fish'],
    bestSeasons: ['summer', 'autumn'], bestTimeOfDay: ['night', 'dusk'],
    diet: ['Fish', 'Invertebrates', 'Carrion'],
    description: 'A mysterious, critically endangered species that spawns in the Sargasso Sea. Every eel caught is precious.',
    funFact: 'European eels spawn in the Sargasso Sea — a journey of over 6,000km from UK rivers.',
    conservationStatus: 'CR', catchDifficulty: 3, category: 'Coarse',
  },
  {
    id: 'bonefish', name: 'Bonefish', scientificName: 'Albula vulpes', family: 'Albulidae',
    rarity: 'epic', rarityLabel: 'Epic', xpBase: 150,
    regions: ['US', 'GLOBAL'], habitat: ['sea', 'estuary'],
    averageWeightKg: 2.0, maxWeightKg: 8.6, worldRecordKg: 8.62, worldRecordLocation: 'Zululand, South Africa',
    bestBaits: ['Shrimp flies', 'Crab patterns', 'Shrimp'],
    bestSeasons: ['spring', 'summer', 'autumn'], bestTimeOfDay: ['morning', 'afternoon'],
    diet: ['Shrimp', 'Crabs', 'Small fish'],
    description: "The 'Ghost of the Flats.' Bonefish are incredibly fast and spooky. Their first run when hooked is explosive.",
    funFact: 'Bonefish can accelerate to 40 mph in short bursts — among the fastest fish in shallow water.',
    conservationStatus: 'NT', catchDifficulty: 4, category: 'Sea',
  },
  {
    id: 'trout-steelhead', name: 'Steelhead Trout', scientificName: 'Oncorhynchus mykiss irideus', family: 'Salmonidae',
    rarity: 'epic', rarityLabel: 'Epic', xpBase: 150,
    regions: ['US', 'CA'], habitat: ['river', 'ocean'],
    averageWeightKg: 4.0, maxWeightKg: 20.0, worldRecordKg: 19.1, worldRecordLocation: 'Bell Island, Alaska',
    bestBaits: ['Roe', 'Spinners', 'Flies', 'Jigs'],
    bestSeasons: ['winter', 'spring'], bestTimeOfDay: ['dawn', 'morning'],
    diet: ['Fish eggs', 'Small fish', 'Insects'],
    description: 'The sea-going form of rainbow trout. Steelhead enter rivers from the Pacific Ocean to spawn, fighting with incredible power.',
    funFact: 'Steelhead are the same species as rainbow trout but have adapted to live in the ocean.',
    conservationStatus: 'NT', catchDifficulty: 5, category: 'Game',
  },
  {
    id: 'florida-bass', name: 'Florida Bass', scientificName: 'Micropterus floridanus', family: 'Centrarchidae',
    rarity: 'epic', rarityLabel: 'Epic', xpBase: 150,
    regions: ['US'], habitat: ['lake', 'reservoir'],
    averageWeightKg: 3.0, maxWeightKg: 10.0, worldRecordKg: 10.09, worldRecordLocation: 'Georgia, USA',
    bestBaits: ['Big swimbaits', 'Shad imitations', 'Topwater', 'Large worms'],
    bestSeasons: ['winter', 'spring'], bestTimeOfDay: ['dawn', 'dusk'],
    diet: ['Shad', 'Sunfish', 'Frogs', 'Crayfish'],
    description: 'The biggest-growing largemouth bass subspecies. Florida strain bass in warm southern waters can grow to legendary proportions.',
    funFact: 'The world largemouth bass record has stood since 1932 at 22lb 4oz.',
    conservationStatus: 'LC', catchDifficulty: 4, category: 'Bass',
  },
  // ── LEGENDARY ──
  {
    id: 'carp-big', name: 'Big Carp (30lb+)', scientificName: 'Cyprinus carpio', family: 'Cyprinidae',
    rarity: 'legendary', rarityLabel: 'Legendary', xpBase: 400,
    regions: ['UK', 'EU'], habitat: ['lake'],
    averageWeightKg: 14.0, maxWeightKg: 45.0, worldRecordKg: 45.59, worldRecordLocation: 'Euro Aqua Lake, Hungary',
    bestBaits: ['Boilies', 'Pop-ups', 'Tigers', 'Snowmen rigs'],
    bestSeasons: ['summer'], bestTimeOfDay: ['night', 'dawn'],
    diet: ['Invertebrates', 'Plant seeds'],
    description: "A 30lb+ carp is every carp angler's dream. These old, wise fish have seen every rig — outsmarting them requires skill, patience, and cunning.",
    funFact: 'The UK record carp weighed over 68lb — caught multiple times from the same lake.',
    conservationStatus: 'VU', catchDifficulty: 5, minLegalSizeCm: 35, category: 'Carp',
  },
  {
    id: 'pike-big', name: 'Big Pike (20lb+)', scientificName: 'Esox lucius', family: 'Esocidae',
    rarity: 'legendary', rarityLabel: 'Legendary', xpBase: 400,
    regions: ['UK', 'IE', 'EU'], habitat: ['lake', 'reservoir'],
    averageWeightKg: 10.0, maxWeightKg: 25.0, worldRecordKg: 25.0, worldRecordLocation: 'Germany',
    bestBaits: ['Large deadbaits', 'Mackerel', 'Herring', 'Big lures'],
    bestSeasons: ['winter', 'autumn'], bestTimeOfDay: ['dawn', 'dusk'],
    diet: ['Fish', 'Waterfowl'],
    description: 'A 20lb+ pike is an extraordinary fish — a true apex predator that has survived decades in rich, productive waters.',
    funFact: 'A pike of this size could be 20+ years old and has likely survived hooks many times.',
    conservationStatus: 'LC', catchDifficulty: 5, minLegalSizeCm: 50, category: 'Predator',
  },
  {
    id: 'porbeagle', name: 'Porbeagle Shark', scientificName: 'Lamna nasus', family: 'Lamnidae',
    rarity: 'legendary', rarityLabel: 'Legendary', xpBase: 400,
    regions: ['UK', 'IE', 'EU', 'US', 'CA'], habitat: ['ocean'],
    averageWeightKg: 80.0, maxWeightKg: 230.0, worldRecordKg: 230.0, worldRecordLocation: 'Caithness, Scotland',
    bestBaits: ['Mackerel', 'Herring', 'Large lures'],
    bestSeasons: ['summer', 'autumn'], bestTimeOfDay: ['morning', 'afternoon'],
    diet: ['Fish', 'Squid', 'Mackerel'],
    description: 'A powerful, warm-bodied shark related to the great white. Porbeagles inhabit deep offshore UK waters and are capable of breathtaking runs.',
    funFact: 'Porbeagles can maintain a body temperature above that of the surrounding water.',
    conservationStatus: 'VU', catchDifficulty: 5, category: 'Sea',
  },
  {
    id: 'muskellunge', name: 'Muskellunge', scientificName: 'Esox masquinongy', family: 'Esocidae',
    rarity: 'legendary', rarityLabel: 'Legendary', xpBase: 400,
    regions: ['US', 'CA'], habitat: ['lake', 'river'],
    averageWeightKg: 7.0, maxWeightKg: 32.0, worldRecordKg: 32.2, worldRecordLocation: 'Lake Court Oreilles, Wisconsin, USA',
    bestBaits: ['Giant lures', 'Jerkbaits', 'Live suckers', 'Glide baits'],
    bestSeasons: ['autumn', 'spring'], bestTimeOfDay: ['dawn', 'dusk'],
    diet: ['Fish', 'Ducks', 'Muskrats'],
    description: "The 'fish of 10,000 casts.' Musky are the most difficult freshwater fish in North America to catch. A trophy requires unparalleled patience.",
    funFact: "Musky are called the 'fish of 10,000 casts' because anglers may fish for years before catching one.",
    conservationStatus: 'LC', catchDifficulty: 5, minLegalSizeCm: 75, category: 'Predator',
  },
  {
    id: 'tarpon', name: 'Tarpon', scientificName: 'Megalops atlanticus', family: 'Megalopidae',
    rarity: 'legendary', rarityLabel: 'Legendary', xpBase: 400,
    regions: ['US'], habitat: ['sea', 'estuary', 'river'],
    averageWeightKg: 40.0, maxWeightKg: 161.0, worldRecordKg: 130.37, worldRecordLocation: 'Lake Maracaibo, Venezuela',
    bestBaits: ['Live mullet', 'Crabs', 'Shrimp', 'Lures'],
    bestSeasons: ['spring', 'summer'], bestTimeOfDay: ['dawn', 'dusk', 'night'],
    diet: ['Fish', 'Crabs', 'Shrimp'],
    description: "The 'Silver King.' Tarpon are prehistoric fish that leap spectacularly when hooked — 6-foot silver fish that explode from the water in crashing jumps.",
    funFact: "Tarpon are one of the oldest fish species alive — haven't changed significantly in 100 million years.",
    conservationStatus: 'VU', catchDifficulty: 5, category: 'Big Game',
  },
  {
    id: 'permit', name: 'Permit', scientificName: 'Trachinotus falcatus', family: 'Carangidae',
    rarity: 'legendary', rarityLabel: 'Legendary', xpBase: 400,
    regions: ['US'], habitat: ['sea', 'estuary'],
    averageWeightKg: 5.0, maxWeightKg: 30.0, worldRecordKg: 23.44, worldRecordLocation: 'Ft. Zach Taylor, Key West, Florida, USA',
    bestBaits: ['Live crabs', 'Crab flies', 'Mantis shrimp'],
    bestSeasons: ['spring', 'summer'], bestTimeOfDay: ['morning', 'afternoon'],
    diet: ['Crabs', 'Shrimp', 'Small fish'],
    description: "The flats fishing holy grail. Permit are notoriously picky, spooky, and difficult to catch on fly or conventional tackle.",
    funFact: 'Many expert fly fishers never catch a permit in their lifetime — the toughest inshore fish.',
    conservationStatus: 'LC', catchDifficulty: 5, category: 'Sea',
  },
  {
    id: 'sailfish', name: 'Sailfish', scientificName: 'Istiophorus platypterus', family: 'Istiophoridae',
    rarity: 'legendary', rarityLabel: 'Legendary', xpBase: 400,
    regions: ['US', 'AUS', 'GLOBAL'], habitat: ['ocean'],
    averageWeightKg: 40.0, maxWeightKg: 100.0, worldRecordKg: 100.24, worldRecordLocation: 'Santa Cruz Island, Ecuador',
    bestBaits: ['Live baits', 'Lures', 'Teasers', 'Trolling baits'],
    bestSeasons: ['summer', 'spring'], bestTimeOfDay: ['morning', 'afternoon'],
    diet: ['Fish', 'Squid', 'Octopus'],
    description: 'The fastest fish in the ocean, capable of 110 km/h bursts. The holy grail of offshore sport fishing, famous for acrobatic leaps.',
    funFact: 'Sailfish can swim at over 110 km/h — the fastest recorded speed of any fish.',
    conservationStatus: 'LC', catchDifficulty: 5, category: 'Big Game',
  },
  {
    id: 'marlin-blue', name: 'Blue Marlin', scientificName: 'Makaira nigricans', family: 'Istiophoridae',
    rarity: 'legendary', rarityLabel: 'Legendary', xpBase: 400,
    regions: ['US', 'AUS', 'GLOBAL'], habitat: ['ocean'],
    averageWeightKg: 100.0, maxWeightKg: 900.0, worldRecordKg: 636.0, worldRecordLocation: 'Vitoria, Brazil',
    bestBaits: ['Trolling lures', 'Live bait', 'Tuna', 'Mackerel'],
    bestSeasons: ['summer', 'spring'], bestTimeOfDay: ['morning', 'afternoon'],
    diet: ['Tuna', 'Squid', 'Dolphinfish'],
    description: 'The ultimate big game fish. Blue marlin are massive, powerful, and absolutely spectacular fighters. Catching one is a bucket-list achievement.',
    funFact: 'Blue marlin can travel 10,000km in a single year across ocean basins.',
    conservationStatus: 'VU', catchDifficulty: 5, category: 'Big Game',
  },
  {
    id: 'bluefin-tuna', name: 'Atlantic Bluefin Tuna', scientificName: 'Thunnus thynnus', family: 'Scombridae',
    rarity: 'legendary', rarityLabel: 'Legendary', xpBase: 400,
    regions: ['UK', 'IE', 'EU', 'US', 'CA'], habitat: ['ocean'],
    averageWeightKg: 150.0, maxWeightKg: 725.0, worldRecordKg: 679.0, worldRecordLocation: 'Aulds Cove, Nova Scotia, Canada',
    bestBaits: ['Mackerel', 'Herring', 'Squid', 'Large lures'],
    bestSeasons: ['summer', 'autumn'], bestTimeOfDay: ['morning', 'afternoon'],
    diet: ['Herring', 'Mackerel', 'Squid'],
    description: 'The most valuable and powerful fish in the ocean. A single Atlantic bluefin tuna can sell for hundreds of thousands at Japanese fish markets.',
    funFact: "A single Atlantic bluefin tuna sold at Tokyo's Tsukiji market for $3.1 million USD.",
    conservationStatus: 'EN', catchDifficulty: 5, category: 'Big Game',
  },
  {
    id: 'salmon-chinook', name: 'Chinook Salmon', scientificName: 'Oncorhynchus tshawytscha', family: 'Salmonidae',
    rarity: 'legendary', rarityLabel: 'Legendary', xpBase: 400,
    regions: ['US', 'CA', 'NZ'], habitat: ['river', 'ocean'],
    averageWeightKg: 12.0, maxWeightKg: 61.0, worldRecordKg: 44.11, worldRecordLocation: 'Kenai River, Alaska, USA',
    bestBaits: ['Roe', 'Prawns', 'Large spoons', 'Plugs'],
    bestSeasons: ['summer', 'spring'], bestTimeOfDay: ['dawn', 'dusk'],
    diet: ['Fish', 'Squid', 'Crustaceans'],
    description: "The 'King Salmon' — the largest Pacific salmon. Chinook can exceed 50kg and fight with extraordinary power.",
    funFact: 'Chinook salmon do not eat during their freshwater migration — they fight on energy reserves alone.',
    conservationStatus: 'LC', catchDifficulty: 5, minLegalSizeCm: 60, category: 'Game',
  },
  {
    id: 'huchen', name: 'Huchen (Danube Salmon)', scientificName: 'Hucho hucho', family: 'Salmonidae',
    rarity: 'legendary', rarityLabel: 'Legendary', xpBase: 400,
    regions: ['EU'], habitat: ['river'],
    averageWeightKg: 8.0, maxWeightKg: 52.0, worldRecordKg: 52.0, worldRecordLocation: 'Austria',
    bestBaits: ['Large lures', 'Live fish', 'Deadbaits', 'Spinners'],
    bestSeasons: ['winter', 'autumn'], bestTimeOfDay: ['dawn', 'dusk'],
    diet: ['Large fish', 'Small mammals', 'Waterfowl'],
    description: 'The Danube salmon — a massive salmonid found only in the Danube river system. Extremely rare, listed as endangered.',
    funFact: 'Huchen are the largest salmonid in European rivers and are listed as endangered.',
    conservationStatus: 'EN', catchDifficulty: 5, category: 'Game',
  },
];

export function getFishById(id: string): FishSpecies | undefined {
  return FISH_DATABASE.find((f) => f.id === id);
}

export function getFishByRarity(rarity: RarityTier): FishSpecies[] {
  return FISH_DATABASE.filter((f) => f.rarity === rarity);
}

export function getFishByRegion(region: Region): FishSpecies[] {
  return FISH_DATABASE.filter((f) => f.regions.includes(region));
}

export function getFishByCategory(category: string): FishSpecies[] {
  return FISH_DATABASE.filter((f) => f.category === category);
}

export function searchFish(query: string): FishSpecies[] {
  const q = query.toLowerCase();
  return FISH_DATABASE.filter(
    (f) =>
      f.name.toLowerCase().includes(q) ||
      f.scientificName.toLowerCase().includes(q) ||
      f.family.toLowerCase().includes(q) ||
      f.category.toLowerCase().includes(q),
  );
}

export const FISH_CATEGORIES = [...new Set(FISH_DATABASE.map((f) => f.category))];
export const FISH_REGIONS: Region[] = ['UK', 'IE', 'EU', 'US', 'CA', 'AUS', 'NZ', 'ZA', 'JP', 'IN', 'BR', 'GLOBAL'];
