export interface FishingSpot {
  id: string;
  name: string;
  country: string;
  region: string;
  lat: number;
  lng: number;
  type: 'lake' | 'river' | 'sea' | 'reservoir' | 'canal' | 'estuary' | 'beach' | 'pier' | 'offshore';
  species: string[];
  description: string;
  bestSeason: string[];
  difficulty: 1 | 2 | 3 | 4 | 5;
  permitRequired: boolean;
  facilities: string[];
  tideDependent: boolean;
  popularBaits: string[];
}

export const FISHING_SPOTS: FishingSpot[] = [
  // ── UK RIVERS ──
  { id: 'river-test-uk', name: 'River Test', country: 'UK', region: 'Hampshire', lat: 51.0574, lng: -1.4870, type: 'river', species: ['Brown Trout', 'Grayling', 'Roach'], description: "England's most famous chalk stream. Crystal-clear waters and wild brown trout make this the ultimate fly fishing destination.", bestSeason: ['spring', 'summer'], difficulty: 4, permitRequired: true, facilities: ['Parking', 'Footpaths'], tideDependent: false, popularBaits: ['Dry flies', 'Nymphs'] },
  { id: 'river-wye-uk', name: 'River Wye', country: 'UK', region: 'Wales/England', lat: 51.9800, lng: -2.7900, type: 'river', species: ['Salmon', 'Pike', 'Barbel', 'Chub'], description: 'One of the UK\'s finest salmon and barbel rivers. The Wye flows through stunning gorges and offers excellent coarse and game fishing.', bestSeason: ['spring', 'autumn'], difficulty: 3, permitRequired: true, facilities: ['Parking', 'B&B nearby'], tideDependent: false, popularBaits: ['Flies', 'Spinners', 'Boilies'] },
  { id: 'river-avon-uk', name: 'Hampshire Avon', country: 'UK', region: 'Hampshire', lat: 50.9200, lng: -1.7700, type: 'river', species: ['Barbel', 'Chub', 'Roach', 'Bream'], description: 'A legendary barbel river. The Hampshire Avon has produced some of the UK\'s biggest barbel and remains a top coarse fishing destination.', bestSeason: ['summer', 'autumn'], difficulty: 3, permitRequired: true, facilities: ['Parking'], tideDependent: false, popularBaits: ['Hemp', 'Meat', 'Boilies'] },
  { id: 'river-severn-uk', name: 'River Severn', country: 'UK', region: 'Worcestershire', lat: 52.1900, lng: -2.2200, type: 'river', species: ['Barbel', 'Chub', 'Bream', 'Pike'], description: "The UK's longest river. The Severn offers superb barbel and chub fishing, especially in autumn when the fish feed hard before winter.", bestSeason: ['autumn', 'summer'], difficulty: 2, permitRequired: true, facilities: ['Parking', 'Facilities nearby'], tideDependent: false, popularBaits: ['Meat', 'Hemp', 'Pellets'] },
  { id: 'river-tay-uk', name: 'River Tay', country: 'UK', region: 'Perthshire, Scotland', lat: 56.4000, lng: -3.4300, type: 'river', species: ['Atlantic Salmon', 'Sea Trout', 'Grayling'], description: "Scotland's mightiest salmon river. The Tay has produced the UK's biggest Atlantic salmon and remains the premier destination for salmon fly fishing.", bestSeason: ['spring', 'autumn'], difficulty: 4, permitRequired: true, facilities: ['Ghillies available', 'Lodges'], tideDependent: false, popularBaits: ['Flies', 'Spinners', 'Worms'] },
  { id: 'river-tweed-uk', name: 'River Tweed', country: 'UK', region: 'Scottish Borders', lat: 55.6800, lng: -2.4400, type: 'river', species: ['Atlantic Salmon', 'Sea Trout', 'Brown Trout'], description: 'The greatest autumn salmon river in the UK. The Tweed\'s famous "back end" salmon run in October is legendary among fly fishers.', bestSeason: ['autumn', 'spring'], difficulty: 4, permitRequired: true, facilities: ['Ghillies', 'Lodges', 'Tackle shops'], tideDependent: false, popularBaits: ['Flies', 'Spinners'] },
  { id: 'river-exe-uk', name: 'River Exe', country: 'UK', region: 'Devon', lat: 50.7200, lng: -3.5200, type: 'river', species: ['Brown Trout', 'Sea Trout', 'Salmon'], description: 'A beautiful Devon river offering wild brown trout and sea trout fishing through stunning moorland and valley scenery.', bestSeason: ['spring', 'summer'], difficulty: 3, permitRequired: true, facilities: ['Parking'], tideDependent: false, popularBaits: ['Wet flies', 'Dry flies', 'Worms'] },
  { id: 'river-thames-uk', name: 'River Thames (Oxford)', country: 'UK', region: 'Oxfordshire', lat: 51.7520, lng: -1.2577, type: 'river', species: ['Barbel', 'Chub', 'Bream', 'Roach', 'Pike'], description: 'The upper Thames around Oxford offers superb coarse fishing for barbel and bream. Excellent all-round river with easy access.', bestSeason: ['summer', 'autumn'], difficulty: 2, permitRequired: true, facilities: ['Parking', 'Pubs nearby'], tideDependent: false, popularBaits: ['Maggots', 'Pellets', 'Boilies'] },
  { id: 'river-nene-uk', name: 'River Nene', country: 'UK', region: 'East Midlands', lat: 52.5800, lng: -0.2400, type: 'river', species: ['Bream', 'Roach', 'Perch', 'Zander'], description: 'A classic Fenland river with excellent bream and roach fishing. Match anglers love the Nene for its prolific head of fish.', bestSeason: ['summer', 'autumn'], difficulty: 1, permitRequired: true, facilities: ['Parking', 'Footpaths'], tideDependent: false, popularBaits: ['Maggots', 'Corn', 'Groundbait'] },
  { id: 'river-great-ouse-uk', name: 'Great Ouse', country: 'UK', region: 'Cambridgeshire', lat: 52.3700, lng: 0.0400, type: 'river', species: ['Bream', 'Roach', 'Zander', 'Pike'], description: 'A prolific Fenland river. The Great Ouse is famous for its monster bream and the presence of big zander throughout its length.', bestSeason: ['summer', 'autumn'], difficulty: 2, permitRequired: true, facilities: ['Parking'], tideDependent: false, popularBaits: ['Maggots', 'Deadbaits', 'Groundbait'] },
  // ── UK LAKES ──
  { id: 'loch-lomond-uk', name: 'Loch Lomond', country: 'UK', region: 'Scotland', lat: 56.0800, lng: -4.5900, type: 'lake', species: ['Pike', 'Perch', 'Roach', 'Trout'], description: "Scotland's largest loch. Loch Lomond offers extraordinary pike fishing and beautiful scenery. Home to some of Scotland's biggest pike.", bestSeason: ['winter', 'autumn'], difficulty: 2, permitRequired: false, facilities: ['Parking', 'Boat hire', 'Cafes'], tideDependent: false, popularBaits: ['Deadbaits', 'Lures', 'Worms'] },
  { id: 'lake-windermere-uk', name: 'Lake Windermere', country: 'UK', region: 'Cumbria', lat: 54.3500, lng: -2.9300, type: 'lake', species: ['Perch', 'Pike', 'Trout', 'Charr'], description: 'England\'s largest natural lake. Windermere has excellent perch and pike fishing, plus the rare Arctic charr found only in a handful of English lakes.', bestSeason: ['autumn', 'winter'], difficulty: 2, permitRequired: true, facilities: ['Boat hire', 'Car parks', 'Hotels'], tideDependent: false, popularBaits: ['Worms', 'Lures', 'Deadbaits'] },
  { id: 'drayton-reservoir-uk', name: 'Drayton Reservoir', country: 'UK', region: 'Northamptonshire', lat: 52.3200, lng: -1.2000, type: 'reservoir', species: ['Rainbow Trout', 'Brown Trout'], description: 'A premier fly fishing reservoir with excellent stocking of rainbow and brown trout. Regular double-figure fish reported.', bestSeason: ['spring', 'summer', 'autumn'], difficulty: 2, permitRequired: true, facilities: ['Parking', 'Lodge', 'Boat hire'], tideDependent: false, popularBaits: ['Dry flies', 'Nymphs', 'Lures'] },
  { id: 'rutland-water-uk', name: 'Rutland Water', country: 'UK', region: 'Leicestershire', lat: 52.6600, lng: -0.6200, type: 'reservoir', species: ['Rainbow Trout', 'Brown Trout'], description: "England's largest reservoir. Rutland Water is world-famous for its trout fishing and regularly produces double-figure rainbows.", bestSeason: ['spring', 'summer', 'autumn'], difficulty: 2, permitRequired: true, facilities: ['Lodge', 'Boat hire', 'Cafe', 'Parking'], tideDependent: false, popularBaits: ['Buzzers', 'Boobies', 'Cormorant patterns'] },
  { id: 'holme-pierrepont-uk', name: 'Holme Pierrepont (Colwick)', country: 'UK', region: 'Nottinghamshire', lat: 52.9390, lng: -1.1000, type: 'lake', species: ['Carp', 'Bream', 'Tench', 'Pike'], description: 'A well-known Nottinghamshire fishery with a variety of species. Regular matches held here on the River Trent pits.', bestSeason: ['spring', 'summer', 'autumn'], difficulty: 2, permitRequired: true, facilities: ['Parking', 'Toilets'], tideDependent: false, popularBaits: ['Boilies', 'Corn', 'Groundbait'] },
  // ── UK SEA ──
  { id: 'chesil-beach-uk', name: 'Chesil Beach', country: 'UK', region: 'Dorset', lat: 50.6200, lng: -2.5500, type: 'beach', species: ['Cod', 'Bass', 'Smoothound', 'Mackerel', 'Plaice'], description: 'One of the UK\'s most iconic shore fishing venues. Chesil Beach\'s shingle shelves steeply into deep water, offering superb off-the-beach fishing.', bestSeason: ['autumn', 'winter'], difficulty: 3, permitRequired: false, facilities: ['Car parks', 'Cafe nearby'], tideDependent: true, popularBaits: ['Lug', 'Squid', 'Peeler crab'] },
  { id: 'dungeness-uk', name: 'Dungeness Point', country: 'UK', region: 'Kent', lat: 50.9100, lng: 0.9800, type: 'beach', species: ['Cod', 'Whiting', 'Bass', 'Smoothound'], description: 'England\'s most famous cod beach. Dungeness produces excellent winter cod fishing, with fish of 20lb+ caught regularly in peak season.', bestSeason: ['autumn', 'winter'], difficulty: 3, permitRequired: false, facilities: ['Parking', 'Pub nearby'], tideDependent: true, popularBaits: ['Lug', 'Black lug', 'Squid cocktail'] },
  { id: 'portland-bill-uk', name: 'Portland Bill', country: 'UK', region: 'Dorset', lat: 50.5150, lng: -2.4560, type: 'sea', species: ['Bass', 'Pollock', 'Mackerel', 'Bream', 'Wrasse'], description: 'A headland with tide races that attract predatory fish year-round. Excellent lure fishing for bass and pollock from the rocks.', bestSeason: ['summer', 'autumn'], difficulty: 4, permitRequired: false, facilities: ['Car park', 'Lighthouse cafe'], tideDependent: true, popularBaits: ['Lures', 'Plugs', 'Feathers'] },
  { id: 'brixham-boats-uk', name: 'Brixham Boat Fishing', country: 'UK', region: 'Devon', lat: 50.3980, lng: -3.5130, type: 'offshore', species: ['Turbot', 'Brill', 'Cod', 'Conger', 'Tope'], description: 'Brixham harbour hosts a large charter boat fleet. The Devon coast offers world-class boat fishing for turbot, conger, and giant tope.', bestSeason: ['summer', 'autumn'], difficulty: 3, permitRequired: false, facilities: ['Harbour', 'Restaurants', 'Charter boats'], tideDependent: false, popularBaits: ['Squid', 'Mackerel', 'Sand eels'] },
  { id: 'noss-head-uk', name: 'Noss Head (Caithness)', country: 'UK', region: 'Scotland', lat: 58.4700, lng: -3.0400, type: 'offshore', species: ['Porbeagle', 'Tope', 'Cod', 'Halibut'], description: 'Scotland\'s northernmost boat fishing. Caithness offers some of the UK\'s most exciting offshore fishing including rare porbeagle shark.', bestSeason: ['summer', 'autumn'], difficulty: 5, permitRequired: false, facilities: ['Harbour', 'Charter boats'], tideDependent: false, popularBaits: ['Mackerel', 'Herring', 'Large lures'] },
  { id: 'swansea-bay-uk', name: 'Swansea Bay', country: 'UK', region: 'Wales', lat: 51.6200, lng: -3.9400, type: 'estuary', species: ['Bass', 'Flatfish', 'Mullet', 'Smoothound'], description: 'A large tidal bay with excellent bass and flatfish fishing. Smoothhounds move in during summer months providing spectacular sport.', bestSeason: ['summer', 'spring'], difficulty: 2, permitRequired: false, facilities: ['Car parks', 'Promenade'], tideDependent: true, popularBaits: ['Peeler crab', 'Lug', 'Ragworm'] },
  // ── IRELAND ──
  { id: 'lough-corrib-ie', name: 'Lough Corrib', country: 'Ireland', region: 'Galway', lat: 53.5000, lng: -9.3000, type: 'lake', species: ['Brown Trout', 'Pike', 'Perch'], description: "Ireland's largest lake. Lough Corrib is world-famous for its mayfly hatch in May — the greatest dry fly trout fishing spectacle in Europe.", bestSeason: ['spring', 'summer'], difficulty: 3, permitRequired: true, facilities: ['Boat hire', 'B&Bs', 'Tackle shops'], tideDependent: false, popularBaits: ['Dry flies', 'Dapping', 'Wet flies'] },
  { id: 'river-shannon-ie', name: 'River Shannon', country: 'Ireland', region: 'Limerick', lat: 52.6630, lng: -8.6250, type: 'river', species: ['Bream', 'Roach', 'Pike', 'Perch'], description: "Europe's second-longest river. The Shannon's vast waterway holds enormous bream shoals and superb pike. A match angler's paradise.", bestSeason: ['summer', 'autumn'], difficulty: 2, permitRequired: true, facilities: ['Multiple access points', 'Towns nearby'], tideDependent: false, popularBaits: ['Maggots', 'Groundbait', 'Deadbaits'] },
  { id: 'clew-bay-ie', name: 'Clew Bay', country: 'Ireland', region: 'Mayo', lat: 53.8000, lng: -9.7000, type: 'estuary', species: ['Bass', 'Mullet', 'Pollock', 'Flatfish'], description: 'A sheltered western bay with excellent bass and mullet fishing. Famous for its 365 islands — one for each day of the year.', bestSeason: ['summer', 'spring'], difficulty: 3, permitRequired: false, facilities: ['Westport nearby', 'Boat hire'], tideDependent: true, popularBaits: ['Worms', 'Lures', 'Bread'] },
  // ── FRANCE / EUROPE ──
  { id: 'euro-aqua-hu', name: 'Euro Aqua', country: 'Hungary', region: 'Rajka', lat: 47.8800, lng: 17.2300, type: 'lake', species: ['Common Carp', 'Mirror Carp', 'Catfish'], description: 'The lake that produced the current world carp record — a 45.59kg mirror carp. Euro Aqua is the world capital of big carp fishing.', bestSeason: ['summer', 'autumn'], difficulty: 5, permitRequired: true, facilities: ['Lodge', 'Boats', 'Guiding'], tideDependent: false, popularBaits: ['Boilies', 'Pop-ups', 'Tigers'] },
  { id: 'river-ebro-es', name: 'River Ebro', country: 'Spain', region: 'Catalonia', lat: 40.8000, lng: 0.5200, type: 'river', species: ['Wels Catfish', 'Carp', 'Pike'], description: "Europe's top catfish venue. The Ebro holds a world-class population of wels catfish, with fish regularly exceeding 2 metres.", bestSeason: ['summer', 'spring'], difficulty: 3, permitRequired: true, facilities: ['Guides', 'Accommodation', 'Boat hire'], tideDependent: false, popularBaits: ['Liver', 'Deadbaits', 'Large lures'] },
  { id: 'lake-como-it', name: 'Lake Como', country: 'Italy', region: 'Lombardy', lat: 45.9800, lng: 9.2600, type: 'lake', species: ['Perch', 'Pike', 'Trout', 'Tench'], description: "Italy's deepest lake. Lake Como offers excellent perch and pike fishing with a stunning Alpine backdrop.", bestSeason: ['spring', 'summer'], difficulty: 2, permitRequired: true, facilities: ['Towns nearby', 'Boat hire', 'Hotels'], tideDependent: false, popularBaits: ['Lures', 'Worms', 'Spinners'] },
  { id: 'danube-au', name: 'River Danube (Vienna)', country: 'Austria', region: 'Vienna', lat: 48.2082, lng: 16.3738, type: 'river', species: ['Huchen', 'Zander', 'Catfish', 'Barbel'], description: 'The Danube near Vienna offers a chance at the legendary huchen (Danube salmon) — one of the most difficult freshwater fish to catch in Europe.', bestSeason: ['winter', 'autumn'], difficulty: 4, permitRequired: true, facilities: ['City nearby', 'Guides'], tideDependent: false, popularBaits: ['Large lures', 'Deadbaits'] },
  { id: 'vistula-river-pl', name: 'River Vistula', country: 'Poland', region: 'Warsaw area', lat: 52.2297, lng: 21.0122, type: 'river', species: ['Zander', 'Asp', 'Catfish', 'Pike'], description: "Poland's largest river. The Vistula hosts excellent zander and asp fishing, plus some of the best asp surface fishing in Europe.", bestSeason: ['summer', 'spring'], difficulty: 3, permitRequired: true, facilities: ['Access points', 'Cities nearby'], tideDependent: false, popularBaits: ['Lures', 'Spinners', 'Deadbaits'] },
  { id: 'ijsselmeer-nl', name: 'IJsselmeer', country: 'Netherlands', region: 'North Holland', lat: 52.7500, lng: 5.2500, type: 'lake', species: ['Perch', 'Eel', 'Bream', 'Pike'], description: "Europe's largest freshwater lake, created by damming the Zuiderzee. Excellent perch fishing with fish to over 3lb.", bestSeason: ['autumn', 'spring'], difficulty: 2, permitRequired: true, facilities: ['Marinas', 'Boat hire'], tideDependent: false, popularBaits: ['Lures', 'Worms', 'Jigs'] },
  // ── USA ──
  { id: 'lake-fork-tx', name: 'Lake Fork', country: 'USA', region: 'Texas', lat: 32.7800, lng: -95.5300, type: 'reservoir', species: ['Largemouth Bass', 'Florida Bass', 'Crappie'], description: "Texas's premier largemouth bass lake. Lake Fork has produced more bass over 13 pounds than anywhere else in the world.", bestSeason: ['winter', 'spring'], difficulty: 3, permitRequired: true, facilities: ['Boat ramps', 'Marinas', 'Lodges'], tideDependent: false, popularBaits: ['Swimbaits', 'Jigs', 'Crankbaits'] },
  { id: 'lake-guntersville-al', name: 'Lake Guntersville', country: 'USA', region: 'Alabama', lat: 34.3600, lng: -86.2400, type: 'reservoir', species: ['Largemouth Bass', 'Striped Bass', 'Crappie'], description: 'The Alabama River reservoir is one of the top bass lakes in the entire USA. Guntersville regularly hosts major professional bass tournaments.', bestSeason: ['spring', 'autumn'], difficulty: 2, permitRequired: true, facilities: ['Boat ramps', 'Guides available', 'Hotels'], tideDependent: false, popularBaits: ['Swimbaits', 'Frogs', 'Spinnerbaits'] },
  { id: 'lake-michigan-wi', name: 'Lake Michigan (Milwaukee)', country: 'USA', region: 'Wisconsin', lat: 43.0389, lng: -87.9065, type: 'lake', species: ['Chinook Salmon', 'Steelhead', 'Brown Trout', 'Walleye'], description: "One of the Great Lakes. Milwaukee's piers and charter boats provide excellent salmon and trout fishing in the world's largest freshwater system.", bestSeason: ['spring', 'autumn'], difficulty: 2, permitRequired: true, facilities: ['Piers', 'Charter boats', 'Marinas'], tideDependent: false, popularBaits: ['Spoons', 'Plugs', 'Live bait'] },
  { id: 'kenai-river-ak', name: 'Kenai River', country: 'USA', region: 'Alaska', lat: 60.5500, lng: -151.2000, type: 'river', species: ['Chinook Salmon', 'Sockeye Salmon', 'Rainbow Trout'], description: "The world's premier Chinook salmon river. The Kenai holds the world record king salmon and annually produces hundreds of fish over 70lbs.", bestSeason: ['summer'], difficulty: 3, permitRequired: true, facilities: ['Guides', 'Lodges', 'Boat hire'], tideDependent: false, popularBaits: ['Roe', 'Spinners', 'Plugs'] },
  { id: 'florida-keys-fl', name: 'Florida Keys', country: 'USA', region: 'Florida', lat: 24.8000, lng: -80.7800, type: 'sea', species: ['Permit', 'Bonefish', 'Tarpon', 'Snook', 'Redfish'], description: "The holy trinity of flats fishing — permit, bonefish, and tarpon. The Florida Keys is the spiritual home of saltwater fly fishing.", bestSeason: ['spring', 'summer'], difficulty: 5, permitRequired: false, facilities: ['Guides', 'Marinas', 'Hotels'], tideDependent: true, popularBaits: ['Live crabs', 'Live shrimp', 'Fly patterns'] },
  { id: 'chesapeake-bay-md', name: 'Chesapeake Bay', country: 'USA', region: 'Maryland/Virginia', lat: 38.5000, lng: -76.1000, type: 'estuary', species: ['Striped Bass', 'Bluefish', 'Red Drum', 'Flounder'], description: "America's largest estuary. The Chesapeake is famous for striped bass (rockfish) and hosts massive runs of migrating fish in spring and autumn.", bestSeason: ['spring', 'autumn'], difficulty: 2, permitRequired: false, facilities: ['Marinas', 'Charter boats', 'Boat ramps'], tideDependent: true, popularBaits: ['Bunker', 'Eels', 'Soft crabs'] },
  { id: 'lake-okeechobee-fl', name: 'Lake Okeechobee', country: 'USA', region: 'Florida', lat: 26.9300, lng: -80.8000, type: 'lake', species: ['Largemouth Bass', 'Florida Bass', 'Crappie', 'Bluegill'], description: "Florida's inland sea. Okeechobee produces some of the biggest bass in the world and offers incredible winter bass fishing.", bestSeason: ['winter', 'spring'], difficulty: 2, permitRequired: true, facilities: ['Boat ramps', 'Guides', 'Lodges'], tideDependent: false, popularBaits: ['Shiners', 'Swimbaits', 'Frogs'] },
  { id: 'lake-erie-oh', name: 'Lake Erie', country: 'USA', region: 'Ohio', lat: 41.6900, lng: -82.6900, type: 'lake', species: ['Walleye', 'Perch', 'Smallmouth Bass', 'Steelhead'], description: "The walleye capital of the world. Lake Erie produces more walleye than any other body of water on earth — trollers fill coolers daily in season.", bestSeason: ['spring', 'autumn'], difficulty: 2, permitRequired: true, facilities: ['Marinas', 'Charter boats'], tideDependent: false, popularBaits: ['Jigs', 'Nightcrawlers', 'Crankbaits'] },
  { id: 'st-lawrence-river-ny', name: 'St. Lawrence River', country: 'USA/Canada', region: 'New York/Ontario', lat: 44.6000, lng: -75.7000, type: 'river', species: ['Smallmouth Bass', 'Muskellunge', 'Northern Pike', 'Walleye'], description: "The world's greatest smallmouth bass river. The St. Lawrence holds extraordinary numbers of large smallmouth and is home to legendary muskellunge.", bestSeason: ['summer', 'autumn'], difficulty: 3, permitRequired: true, facilities: ['Guides', 'Marinas', 'Lodges'], tideDependent: false, popularBaits: ['Tubes', 'Jigs', 'Giant lures'] },
  { id: 'columbia-river-or', name: 'Columbia River', country: 'USA', region: 'Oregon/Washington', lat: 45.5800, lng: -122.6800, type: 'river', species: ['Chinook Salmon', 'Steelhead', 'Sturgeon', 'Walleye'], description: "The Pacific Northwest's greatest river. The Columbia has incredible salmon runs and holds trophy white sturgeon — a living dinosaur.", bestSeason: ['spring', 'summer', 'autumn'], difficulty: 3, permitRequired: true, facilities: ['Guides', 'Boat ramps'], tideDependent: true, popularBaits: ['Roe', 'Plugs', 'Prawns'] },
  { id: 'outer-banks-nc', name: 'Outer Banks', country: 'USA', region: 'North Carolina', lat: 35.5600, lng: -75.4700, type: 'beach', species: ['Red Drum', 'Striped Bass', 'Flounder', 'Bluefish'], description: "America's most famous surf fishing destination. The Outer Banks offers legendary red drum and striped bass fishing from its wild beaches.", bestSeason: ['autumn', 'spring'], difficulty: 2, permitRequired: false, facilities: ['Vehicle beach access', 'Tackle shops'], tideDependent: true, popularBaits: ['Pyramid sinkers', 'Cut mullet', 'Bloodworms'] },
  { id: 'montauk-ny', name: 'Montauk Point', country: 'USA', region: 'New York', lat: 41.0720, lng: -71.8574, type: 'sea', species: ['Striped Bass', 'Bluefish', 'Tuna', 'Mahi-Mahi'], description: "The 'Fishing Capital of the World.' Montauk Point offers legendary striped bass fishing from the rocks plus blue-water offshore action.", bestSeason: ['autumn', 'spring'], difficulty: 3, permitRequired: false, facilities: ['Charter boats', 'Tackle shops', 'Parking'], tideDependent: true, popularBaits: ['Eels', 'Bunker', 'Lures'] },
  // ── AUSTRALIA ──
  { id: 'kakadu-nt-aus', name: 'Kakadu National Park', country: 'Australia', region: 'Northern Territory', lat: -13.0000, lng: 132.5000, type: 'river', species: ['Barramundi', 'Saratoga', 'Sooty Grunter'], description: "Australia's iconic barramundi territory. The billabongs and river systems of Kakadu produce spectacular barra fishing in stunning wilderness.", bestSeason: ['autumn', 'winter'], difficulty: 4, permitRequired: true, facilities: ['Guided trips', 'Camping'], tideDependent: false, popularBaits: ['Lures', 'Live bait', 'Soft plastics'] },
  { id: 'lake-eildon-vic', name: 'Lake Eildon', country: 'Australia', region: 'Victoria', lat: -37.2300, lng: 145.9000, type: 'reservoir', species: ['Rainbow Trout', 'Brown Trout', 'Redfin', 'Murray Cod'], description: "Victoria's premier trout reservoir. Lake Eildon is a massive highland impoundment offering superb trolling and fly fishing for trout.", bestSeason: ['autumn', 'winter', 'spring'], difficulty: 2, permitRequired: true, facilities: ['Marinas', 'Camping', 'Boat hire'], tideDependent: false, popularBaits: ['Lures', 'Worms', 'Flies'] },
  { id: 'sydney-harbour-nsw', name: 'Sydney Harbour', country: 'Australia', region: 'New South Wales', lat: -33.8500, lng: 151.2100, type: 'estuary', species: ['Snapper', 'Flathead', 'Bream', 'Kingfish'], description: "The world's most scenic fishing spot. Sydney Harbour provides excellent urban fishing for bream, snapper, and the powerful kingfish.", bestSeason: ['spring', 'summer'], difficulty: 2, permitRequired: false, facilities: ['Boat ramps', 'Public wharves', 'Charter boats'], tideDependent: true, popularBaits: ['Lures', 'Live bait', 'Prawns'] },
  { id: 'great-barrier-reef-qld', name: 'Great Barrier Reef', country: 'Australia', region: 'Queensland', lat: -18.2861, lng: 147.6992, type: 'offshore', species: ['Black Marlin', 'Sailfish', 'Wahoo', 'Giant Trevally'], description: "The world's greatest reef and a big game fishing mecca. Cairns is the black marlin capital of the world — giants over 1000lb are caught here.", bestSeason: ['autumn', 'winter'], difficulty: 5, permitRequired: false, facilities: ['Charter boats', 'Cairns nearby'], tideDependent: false, popularBaits: ['Live bait', 'Lures', 'Rigged baits'] },
  { id: 'snowy-river-nsw', name: 'Snowy River', country: 'Australia', region: 'New South Wales', lat: -36.5000, lng: 148.7000, type: 'river', species: ['Brown Trout', 'Rainbow Trout'], description: "Australia's most iconic trout river, immortalised in the 'Man from Snowy River.' Crystal-clear alpine waters with wild brown and rainbow trout.", bestSeason: ['spring', 'summer'], difficulty: 3, permitRequired: true, facilities: ['Camping', 'Parking'], tideDependent: false, popularBaits: ['Dry flies', 'Nymphs', 'Spinners'] },
  // ── NEW ZEALAND ──
  { id: 'tongariro-river-nz', name: 'Tongariro River', country: 'New Zealand', region: 'Taupo', lat: -38.8700, lng: 175.7800, type: 'river', species: ['Rainbow Trout', 'Brown Trout'], description: "New Zealand's most famous trout river. The Tongariro receives the world's most prolific trout run — fish averaging over 4kg throughout winter.", bestSeason: ['winter', 'autumn'], difficulty: 3, permitRequired: true, facilities: ['Guides', 'B&Bs', 'Tackle shops'], tideDependent: false, popularBaits: ['Flies', 'Roe', 'Spinners'] },
  { id: 'lake-taupo-nz', name: 'Lake Taupo', country: 'New Zealand', region: 'Taupo', lat: -38.7800, lng: 175.9000, type: 'lake', species: ['Rainbow Trout', 'Brown Trout'], description: "New Zealand's largest lake. Taupo is world-famous for its rainbow trout, with boat fishing and fly fishing producing fish to 15lb+.", bestSeason: ['autumn', 'winter'], difficulty: 2, permitRequired: true, facilities: ['Boat hire', 'Guides', 'Hotels'], tideDependent: false, popularBaits: ['Trolling lures', 'Dry flies', 'Harling'] },
  // ── SOUTH AFRICA ──
  { id: 'cape-point-za', name: 'Cape Point', country: 'South Africa', region: 'Western Cape', lat: -34.3568, lng: 18.4731, type: 'sea', species: ['Yellowtail', 'Geelbek', 'Snoek', 'Hottentot'], description: "The meeting of two oceans. Cape Point offers world-class rock and surf fishing in a spectacular national park setting.", bestSeason: ['winter', 'autumn'], difficulty: 3, permitRequired: true, facilities: ['National park', 'Parking', 'Cafe'], tideDependent: true, popularBaits: ['Lures', 'Squid', 'Cut bait'] },
  { id: 'st-lucia-za', name: "St Lucia Estuary", country: 'South Africa', region: 'KwaZulu-Natal', lat: -28.3700, lng: 32.4200, type: 'estuary', species: ['Bonefish', 'Kingfish', 'Barracuda', 'Cob'], description: "Africa's largest estuarine system. St Lucia is a UNESCO World Heritage Site with extraordinary fishing in pristine conditions.", bestSeason: ['spring', 'summer'], difficulty: 2, permitRequired: true, facilities: ['Lodges', 'Guides', 'Boat hire'], tideDependent: true, popularBaits: ['Lures', 'Live bait', 'Flies'] },
  // ── JAPAN ──
  { id: 'hokkaido-salmon-jp', name: 'Tokachi River', country: 'Japan', region: 'Hokkaido', lat: 42.9000, lng: 143.2000, type: 'river', species: ['Chinook Salmon', 'Masu Trout', 'Dolly Varden'], description: "Hokkaido's premier salmon river. The Tokachi river system offers spectacular autumn salmon runs in pristine Japanese wilderness.", bestSeason: ['autumn', 'summer'], difficulty: 4, permitRequired: true, facilities: ['Guides', 'Ryokan nearby'], tideDependent: false, popularBaits: ['Spoons', 'Spinners', 'Flies'] },
  // ── CANADA ──
  { id: 'campbell-river-bc', name: 'Campbell River', country: 'Canada', region: 'British Columbia', lat: 50.0164, lng: -125.2443, type: 'river', species: ['Chinook Salmon', 'Coho Salmon', 'Steelhead'], description: "The salmon capital of the world. Campbell River hosts incredible chinook and coho runs, with fish regularly exceeding 40lbs.", bestSeason: ['summer', 'autumn'], difficulty: 3, permitRequired: true, facilities: ['Guides', 'Marinas', 'Hotels'], tideDependent: false, popularBaits: ['Herring', 'Spinners', 'Plugs'] },
  { id: 'lake-of-the-woods-on', name: 'Lake of the Woods', country: 'Canada', region: 'Ontario', lat: 49.6000, lng: -94.5000, type: 'lake', species: ['Walleye', 'Muskellunge', 'Northern Pike', 'Smallmouth Bass'], description: "A legendary Ontario lake with over 14,000 islands. Lake of the Woods is one of North America's top walleye and musky destinations.", bestSeason: ['summer', 'autumn'], difficulty: 2, permitRequired: true, facilities: ['Lodges', 'Boat hire', 'Guides'], tideDependent: false, popularBaits: ['Jigs', 'Giant lures', 'Live bait'] },
  // ── BRAZIL ──
  { id: 'amazon-river-br', name: 'Rio Negro (Amazon)', country: 'Brazil', region: 'Amazonas', lat: -3.1500, lng: -60.0200, type: 'river', species: ['Peacock Bass', 'Arapaima', 'Piranha'], description: "The world's most biodiverse freshwater system. Fishing the Amazon for peacock bass is an extraordinary bucket-list experience.", bestSeason: ['autumn', 'winter'], difficulty: 4, permitRequired: true, facilities: ['Liveaboards', 'Lodges', 'Guides'], tideDependent: false, popularBaits: ['Large lures', 'Topwater', 'Buzzbaits'] },
  // ── MORE UK SPOTS ──
  { id: 'loch-awe-uk', name: 'Loch Awe', country: 'UK', region: 'Argyll, Scotland', lat: 56.2900, lng: -5.0600, type: 'lake', species: ['Brown Trout', 'Rainbow Trout', 'Pike', 'Perch'], description: "Scotland's longest loch. Loch Awe offers superb trout and pike fishing amid stunning Highland scenery.", bestSeason: ['spring', 'summer', 'autumn'], difficulty: 2, permitRequired: true, facilities: ['Boat hire', 'Car parks', 'Hotels'], tideDependent: false, popularBaits: ['Wet flies', 'Deadbaits', 'Worms'] },
  { id: 'blenheim-palace-uk', name: 'Blenheim Palace Lake', country: 'UK', region: 'Oxfordshire', lat: 51.8400, lng: -1.3600, type: 'lake', species: ['Carp', 'Bream', 'Tench', 'Pike'], description: 'Fishing in the grounds of a UNESCO World Heritage Site. Blenheim Palace lake holds huge carp in a spectacular stately home setting.', bestSeason: ['spring', 'summer'], difficulty: 3, permitRequired: true, facilities: ['Parking', 'Cafe in palace'], tideDependent: false, popularBaits: ['Boilies', 'Corn', 'Bread'] },
  { id: 'bass-rock-uk', name: 'Bass Rock (Firth of Forth)', country: 'UK', region: 'East Lothian, Scotland', lat: 56.0760, lng: -2.6430, type: 'sea', species: ['Cod', 'Bass', 'Mackerel', 'Pollack'], description: 'Boat fishing around Bass Rock in the Firth of Forth. The strong tides concentrate baitfish and attract large predatory species.', bestSeason: ['summer', 'autumn'], difficulty: 3, permitRequired: false, facilities: ['North Berwick harbour', 'Charter boats'], tideDependent: true, popularBaits: ['Feathers', 'Lures', 'Pirks'] },
];

export function getSpotById(id: string): FishingSpot | undefined {
  return FISHING_SPOTS.find((s) => s.id === id);
}

export function getSpotsByCountry(country: string): FishingSpot[] {
  return FISHING_SPOTS.filter((s) => s.country === country);
}

export function getSpotsByType(type: FishingSpot['type']): FishingSpot[] {
  return FISHING_SPOTS.filter((s) => s.type === type);
}

export function searchSpots(query: string): FishingSpot[] {
  const q = query.toLowerCase();
  return FISHING_SPOTS.filter(
    (s) =>
      s.name.toLowerCase().includes(q) ||
      s.country.toLowerCase().includes(q) ||
      s.region.toLowerCase().includes(q) ||
      s.species.some((sp) => sp.toLowerCase().includes(q)),
  );
}

export function getNearbySpots(lat: number, lng: number, radiusKm = 200): FishingSpot[] {
  return FISHING_SPOTS.filter((s) => {
    const dLat = (s.lat - lat) * (Math.PI / 180);
    const dLng = (s.lng - lng) * (Math.PI / 180);
    const a =
      Math.sin(dLat / 2) * Math.sin(dLat / 2) +
      Math.cos(lat * (Math.PI / 180)) * Math.cos(s.lat * (Math.PI / 180)) *
      Math.sin(dLng / 2) * Math.sin(dLng / 2);
    const c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a));
    return 6371 * c <= radiusKm;
  });
}

export const SPOT_COUNTRIES = [...new Set(FISHING_SPOTS.map((s) => s.country))].sort();
